### ISSUE TITLE
How to get all roadblock_connector in an intersection?

### ISSUE THREAD

**Issue by fsgdrq** [motional/nuplan-devkit#102]
Hi,

While using the devkit I encountered the following confusion. There seem to be few functional functions under Class NuPlanIntersection. How to get the information of all roadblock_connectors in an intersection and their direction?

Thanks.

**Comment by patk-motional** [comment]
Hi @fsgdrq,

You can get them from NuPlanRoadBlockConnector instead. NuPlanIntersection only represents the polygon area of the intersection
