### ISSUE TITLE
pyogrio load map gpkg error 

### ISSUE THREAD

**Issue by Yuddicpp** [motional/nuplan-devkit#104]
result = ogr_read(
  File "pyogrio/_io.pyx", line 841, in pyogrio._io.ogr_read
  File "pyogrio/_io.pyx", line 144, in pyogrio._io.ogr_open
pyogrio.errors.DataSourceError: database is locked: this file is a WAL-enabled database. It cannot be opened because it is presumably read-only or in a read-only directory.

**Comment by mspryn-motional** [comment]
Is the DB in a read-only directory? Does your user have read permissions (which can be checked with `ls -l db_file`)?

If you don't, you can assign ownership with `sudo chown -R $USER:$USER /path/to/file`

**Comment by gianmarco-motional** [comment]
I'll close the issue for inactivity. If you still are facing the problem with the current devkit version, feel free to reopen it!
