### ISSUE TITLE
Same scenaio information with different token and type?

### ISSUE THREAD

**Issue by Kguo-cs** [motional/nuplan-devkit#111]
I find that the scenario with token " '2ff19d873c7553c3' and scenario with token "'0ae17e596fc45545'" has the same start_time and end_time, tracked_objects and map_name. However, their scenario_type are "'stationary_at_traffic_light_without_lead' and 'unknown'. Why?

**Comment by patk-motional** [comment]
Hi @Kguo-cs,

Sorry for the late reply. We are investigating this!
