### ISSUE TITLE
Other connection relationship?

### ISSUE THREAD

**Issue by wangjunhe8127** [motional/nuplan-devkit#112]
*Ex. What is a lane connector? or How many wheels do your vehicles have?*
Hi,where can i get the connetion relationship like left and right? 
thank you~

**Comment by patk-motional** [comment]
Hi @wangjunhe8127,
You can take a look at the function [adjacent_edges()](https://github.com/motional/nuplan-devkit/blob/master/nuplan/common/maps/nuplan_map/lane.py#L118)

**Comment by wangjunhe8127** [comment]
thanks you! 
I find the connection in class "vector_map" is always 1, have not found 2, 3, 4.
So, it need we compute it using adjacent_edges()？

**Comment by wangjunhe8127** [comment]
> Hi @wangjunhe8127, You can take a look at the function [adjacent_edges()](https://github.com/motional/nuplan-devkit/blob/master/nuplan/common/maps/nuplan_map/lane.py#L118)

thanks you!
I find the connection in class "vector_map" is always 1, have not found 2, 3, 4.
So, it need we compute it using adjacent_edges()？

**Comment by gianmarco-motional** [comment]
I'll close the issue for inactivity. If you still are facing the problem with the current devkit version, feel free to reopen it!
