### ISSUE TITLE
An undefined variable self._intial_lidar_token in  nuplan_scenario.py

### ISSUE THREAD

**Issue by SChrisLin** [motional/nuplan-devkit#113]
### Describe the bug

In **nuplan_scenario.py** (v0.5), line 214, there is an undefined variable `self._intial_lidar_token`, but it is passed as a parameter to the function `get_lidar_transform_matrix_for_lidarpc_token_from_db()`. I think it is a typo, and it should be `self._initial_lidar_token`, which is defined in line 79.

```shell
def get_lidar_to_ego_transform(self) -> Transform:
    """Inherited, see superclass."""
    return get_lidar_transform_matrix_for_lidarpc_token_from_db(self._log_file, self._intial_lidar_token)
```

**Comment by michael-motional** [comment]
Thanks for catching this! The fix will be included in the coming release
