### ISSUE TITLE
The competition time

### ISSUE THREAD

**Issue by wangjunhe8127** [motional/nuplan-devkit#114]
Hi, I want to know the competition time,could you tell me?

**Comment by patk-motional** [comment]
Hi @wangjunhe8127,

We are working out some small details on our side. We are planning to open for submission within the next week or two. Stay tuned for updates!

**Comment by wangjunhe8127** [comment]
> 
I see，and could you tell me how long will the competition last?

**Comment by patk-motional** [comment]
Until mid-November before NeurIPS
