### ISSUE TITLE
More property in features

### ISSUE THREAD

**Issue by Shi-Qi-Li** [motional/nuplan-devkit#115]
Hi，
I notice there are some potentially useful properties not included in the current feature class，e.g. the category of agents(Agents class) and the speed limit (Vectormap Class). 
I'm wondering if I need to modify the preprocess to add these properties by myself or if the official team will provide these in a future release.

**Comment by patk-motional** [comment]
Hi @Shi-Qi-Li,

Please think of our implementation as a starting out for you to experiment with. Feel free to add these features yourself. In saying that, we are exploring these features ourselves, but we do not have an expected release date.

**Comment by Shi-Qi-Li** [comment]
Got it! Thank you for your reply!
