### ISSUE TITLE
Nuplan dataset: how to retrieve images

### ISSUE THREAD

**Issue by YENA929** [motional/nuplan-devkit#116]
Hello!
I’m trying to train my model using nuplan dataset but without nuplan framework, the problem occured when I tried to retrieve image from the dataset, Image.filename suggested that the images was stored at root: ~/nuplan/dataset/mini/logname(2021.06.14.16.48.02_veh-12_04978_05337.db)/filename.jpg, but the logname directory didn’t exist! The mini directory only contains .db files instead of dicretories. Maybe I should call some functions to extract the images from .db files? I browsed the devkit but failed to find.

**Comment by JingyuQian** [comment]
Hello,
If you're talking about sensor images, they're not available yet (Motional states they'll release 10% of raw data later sometime). So the filename is just a placeholder at the moment and db files contain no raw data.

**Comment by patk-motional** [comment]
Hi @YENA929,

Please refer to this [issue](https://github.com/motional/nuplan-devkit/issues/42). The short answer is we have released the sensor data yet. We are planning on doing so before the end of the year. We will announce when it is released.
