### ISSUE TITLE
Can't load scenario using cached data?

### ISSUE THREAD

**Issue by Jeff09** [motional/nuplan-devkit#117]
Hi, 

Thank you for such wonderful repo. I just found there might be issues when I use create_scenario_from_paths.py to load cached data. 

First, at https://github.com/motional/nuplan-devkit/blob/update-devkit-v0.4/nuplan/planning/script/builders/scenario_builder.py#L179, the log_name seems to path.parent.name not path.parent.parent.name. 

Second, when using CachedScenario class, it'll also have some NotImplementedError coming out. It looks like it should use NuplanScenario class. 

Thank you for your replies.

**Comment by mspryn-motional** [comment]
Hello. 

For (1): When was the cache created? There was recently a change to add `scenario_type` to the cache path, so it may need to be regenerated.

For (2): This is by design. `CachedScenario` is merely a wrapper that contains enough information to load the scenario from a precomputed cache. It is not intended to be used for actually computing features. Can you provide a little more information about which methods you  are hitting the `NotImplementedErrors` with?

**Comment by Jeff09** [comment]
Hello, 

Thank you for replying. 

For 1), I used the Nuplan-devkit 0.3 version of cache function, not use the latest version to generate the cache. And that might be the problem. 

For 2), when I loaded the precomputed cache, at https://github.com/motional/nuplan-devkit/blob/update-devkit-v0.4/nuplan/planning/script/builders/scenario_builder.py#L178, the scenarios use `CachedScenario` wrapper class, not using `NuplanScenario` class to do the actually computing features. Here's the screenshot to show the error. 
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/13411170/188745453-c7394e85-4744-4fac-8a3d-1be632f8e7eb.png">

**Comment by Jeff09** [comment]
@mspryn-motional @patk-motional 
Hi, I have regenerated the cache data using Nuplan-devkit 0.5 version, but it still can't training the model using cached data. 
There're 511215 scenarios extracted for training in the nuplan-mini dataset. Here's the screenshot to show the error. 
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/13411170/190016128-db1098e1-381a-4282-9da2-cca0af4823d5.png">

In the Nuplan-devkit 0.3 version, the cached data is loaded by the `NuplanScenario` class at the following line. https://github.com/motional/nuplan-devkit/blob/3a4dba5fc6bab7319fb2855eb9d9867eb17336b3/nuplan/planning/script/builders/scenario_builder.py#L113 
That's why i'm confused here. Do I need to implement a new cached nuplanscenario class inherited from `CachedScenario `?

**Comment by Jeff09** [comment]
#128

**Comment by patk-motional** [comment]
Hi @Jeff09,

Sorry for the late reply. Has this issue been resolved for you since the v1.0 release?

**Comment by Jeff09** [comment]
Hi @patk-motional, 

Thank you for asking. The problem is still exist in the v1.0 release. The line will raise error when loading cache data. https://github.com/motional/nuplan-devkit/blob/d12f45b63c72d06aac503b12ee18d61a4fdc5c32/nuplan/planning/script/builders/scenario_builder.py#L77
