### ISSUE TITLE
segment in group's growth direction

### ISSUE THREAD

**Issue by wangjunhe8127** [motional/nuplan-devkit#119]
Ex, I want to confirm that whether ego running in the same direction as its recent segment growth

**Comment by gianmarco-motional** [comment]
Hi @wangjunhe8127!
What do you mean with "recent segment growth"?

**Comment by wangjunhe8127** [comment]
> Hi @wangjunhe8127! What do you mean with "recent segment growth"?

for example,

Here are some segments groups named "A" around the ego's target traj, 
the segments in a group "B" which belong to A,
the idx that the closest segment between B and traj's start  is smaller than 
the idx that the closest segment between B and traj's end

it means the ego can not back up.

Is this correct？

see super link https://github.com/wangjunhe8127/tmp/blob/main/2022-09-13_11-36.png

**Comment by patk-motional** [comment]
Hi @wangjunhe8127,

Sorry for the late reply. Has this issue been solved? The diagram is quite hard to read and I'm not sure I understand your point
