### ISSUE TITLE
Install problem when pip install -e .

### ISSUE THREAD

**Issue by retrospectmike** [motional/nuplan-devkit#12]
I get to this error following verbatim the steps in the [installation guide](https://github.com/motional/nuplan-devkit/blob/master/docs/installation.md).

At the step where you  run:
`pip install -e .` as recommended in the Setup portion of the Readme, fails.

```
...
    Complete output (1 lines):
    error in nuplan-devkit setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at "'-f https'": Expected W:(abcd...)
...
```

As the error mentions the problem is something in the line in requirements.txt first line where it references:
` -f https://download.pytorch.org/whl/torch_stable.html`

It may be a problem with pip-install ?  Removing that one line from requirements.txt solves it however you'd be losing that necesary dependency.
On the other hand you could manually get the depencies using:
`python -m pip install -r requirements.txt ` with requirements.txt as is and it completes gathering the depencies.

**Comment by kokseang-motional** [comment]
Hi, thanks for the reporting. 
We have a PR to fix that. 
https://github.com/motional/nuplan-devkit/pull/21
