### ISSUE TITLE
Possible mistake in combined overall score calculation

### ISSUE THREAD

**Issue by jchengai** [motional/nuplan-devkit#125]
FYI, 

I think the combined_overall_score in

https://github.com/motional/nuplan-devkit/blob/d1d654e1df30e3ac5ac1690c3240a09a18fe4d66/nuplan/submission/evalai/leaderboard_writer.py#L53

should be

```python
np.mean([ch1['score'].values[0], ch2['score'].values[0], ch3['score'].values[0]])
```

**Comment by gianmarco-motional** [comment]
@jchengai Thanks for bringing this up, I will get to it ASAP
