### ISSUE TITLE
Execution fails in the tutorial notbeook nuplan_framework.ipynb 

### ISSUE THREAD

**Issue by retrospectmike** [motional/nuplan-devkit#13]
Execution fails in the tutorial notbeook nuplan_framework.ipynb at the following block:
![image](https://user-images.githubusercontent.com/69996986/146589985-dc04e297-eb57-49bf-a131-8c291cd8ca47.png)

Full dump of outputs with output trace is attached.  
[message from Launch training (within the notebook).txt](https://github.com/motional/nuplan-devkit/files/7737027/message.from.Launch.training.within.the.notebook.txt)

**Comment by kokseang-motional** [comment]
Hi @retrospectmike,
Thanks for reporting the issue to us, it seems that the reason for this error is CUDA, could u double check that you have installed the correct pytorch version and CUDA.
However, if you want to try the tutorial, I suggest you to place this flag to disable gpu training.

`'gpu=False'  `

**Comment by kokseang-motional** [comment]
Specifically, you could change cfg to:

```
cfg = hydra.compose(config_name=CONFIG_NAME, overrides=[
    f'group={str(SAVE_DIR)}',
    f'cache_dir={str(SAVE_DIR)}/cache',
    f'experiment_name={EXPERIMENT}',
    'py_func=train',
    '+training=training_raster_model',  # raster model that consumes ego, agents and map raster layers and regresses the ego's trajectory
    'gpu=False',
    'scenario_builder=nuplan_mini',  # use nuplan mini database
    'scenario_builder.nuplan.scenario_filter.limit_scenarios_per_type=500',  # Choose 500 scenarios to train with
    'scenario_builder.nuplan.scenario_filter.subsample_ratio=0.01',  # subsample scenarios from 20Hz to 0.2Hz
    'lightning.trainer.params.accelerator=ddp',  # ddp is not allowed in interactive environment, using ddp_spawn instead - this can bottleneck the data pipeline, it is recommended to run training outside the notebook
    'lightning.trainer.params.max_epochs=10',
    'data_loader.params.batch_size=1',
    'data_loader.params.num_workers=1',
])
```
