### ISSUE TITLE
nuplan simulator for RL environment

### ISSUE THREAD

**Issue by YENA929** [motional/nuplan-devkit#130]
I've been working on nuplan dataset with RL algorithm, which requires an environment like gym.env, is there anything similar in nuplan which can generate next observation(next ego_state, whether a clash occurs, ...) based on actions like turning angle and throttle

**Comment by JingyuQian** [comment]
I've been playing with nuplan for some time and I think the answer is no. Training in nuplan is fully open-loop. 
A possible idea is to connect nuplan data to other RL frameworks such as [this](https://github.com/HorizonRobotics/alf). That would, however, require a lot of engineering work.

**Comment by YENA929** [comment]
THANKS!!!!!&nbsp;
&nbsp;
------------------

&nbsp;
***@***.***



&nbsp;




------------------&nbsp;Original message&nbsp;------------------
From: "Jingyu_Qian"; 
Sendtime: Friday, Sep 23, 2022 1:37 PM
To: "motional/nuplan-devkit"; 
Cc: " ***@***.***>; "Author"; 
Subject: Re: [motional/nuplan-devkit] nuplan simulator for RL environment (Issue #130)





 
I've been playing with nuplan for some time and I think the answer is no. Training in nuplan is fully open-loop.
 A possible idea is to connect nuplan data to other RL frameworks such as this. That would, however, require a lot of engineering work.

**Comment by gianmarco-motional** [comment]
@YENA929 as mentioned by @JingyuQian   it is currently not possible. It's one of the features we are considering to add in the future, but it will not be added for this competition.
