### ISSUE TITLE
Can we customize the radius of the scenario map during the match

### ISSUE THREAD

**Issue by zqbAse** [motional/nuplan-devkit#134]
The map extracte directly from the radius has a lot of invalid information, so I want to extract 150 meters in front of the ego and 50 meters behind the ego. Can this feature be supported in the match.

**Comment by gianmarco-motional** [comment]
Hi @zqbAse!

Are you talking about features to be used as input to the planner? And to clarify, as `match` you mean the competition?

If so, you can implement your own features, you have access to everything that is passed by PlannerInitialization and PlannerInput. As long as these features as computed as part of the `compute_trajectory` function, you have full control.

Feel free to reopen the issue if I did not answer your question :slightly_smiling_face:
