### ISSUE TITLE
Not all scenarios have corresponding goal, right?

### ISSUE THREAD

**Issue by CrisCloseTheDoor** [motional/nuplan-devkit#137]
Hello, developers!
I would like to know whether all scenarios have its corresponding goal or not. Because when I use `scenario.get_mission_goal()`, sometimes it returns `None` and sometimes I can get the goal.

**Comment by patk-motional** [comment]
Hi @CrisCloseTheDoor,

The short answer is no, not all scenarios have valid mission goals. You can set `scenario_filter.remove_invalid_goals=true` to filter out scenarios without valid goals. In parallel to this, we are on the verge of releasing a new dataset v1.1 that has better route plans and mission goal coverage.

**Comment by CrisCloseTheDoor** [comment]
> 

OK, thank you -D

**Comment by CrisCloseTheDoor** [comment]
> Hi @CrisCloseTheDoor,
> 
> The short answer is no, not all scenarios have valid mission goals. You can set `scenario_filter.remove_invalid_goals=true` to filter out scenarios without valid goals. In parallel to this, we are on the verge of releasing a new dataset v1.1 that has better route plans and mission goal coverage.

Thank you.
BTW, do all test datasets have goal and route so that we can use these information to train a model?

**Comment by gianmarco-motional** [comment]
Yes, test dataset will have valid goal and route
