### ISSUE TITLE
Can a model return multi results including the prediction？

### ISSUE THREAD

**Issue by CrisCloseTheDoor** [motional/nuplan-devkit#138]
Hi developer!
I wonder if the `TorchModuleWrapper` could return several results, all of which are used to calculate the loss, and one of them is the predicted trajectory result? If yes, how does the simulation know which result to use?

**Comment by patk-motional** [comment]
Hi @CrisCloseTheDoor,

The main thing we ask for is to implement the `AbstractPlanner` class and specifically the abstract function `compute_planner_trajectory()`. How you wrap your ML model in this class is up to you.

Now I suspect the confusion stems from the `MLPlanner` class that we have as an **example** of how you could wrap an ML-based planner under the `AbstractPlanner` class. You are free to modify the MLPlanner class however you like. In its current state, the MLPlanner expects that the `TorchModuleWrapper` outputs a `Trajectory` feature [here](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/simulation/planner/ml_planner/ml_planner.py#L58).

I want to stress two things:
1.  Make sure that the `AbstractPlanner` class is implemented correctly
2. You can modify `MLPlanner` if you wish to you it as a starting point for your ML-based planner

Hope this clears it up :)

**Comment by CrisCloseTheDoor** [comment]
Thanks for a very timely reply, I'll check it.
