### ISSUE TITLE
Question about nuplan_framework.ipynb (package version conflicts and version of protobuf)

### ISSUE THREAD

**Issue by IvanChen777** [motional/nuplan-devkit#142]
Hi, I have a problem about running nuplan_framework.ipynb, after I install the environment by following the instruction, this error appears, then I follow the error instruction, and change the version of protobuf to 3.20.x, and also try the second method, it seems not working... and also I find that there will be a conflict if I change the version of protobuf. Do you have some suggestions? Thank you 🙂
<img width="926" alt="截屏2022-10-06 22 22 37" src="https://user-images.githubusercontent.com/91310432/194411082-20cf94e5-f78b-421d-aaf1-0f8115fbe5e3.png">
<img width="1247" alt="截屏2022-10-06 22 22 48" src="https://user-images.githubusercontent.com/91310432/194411123-73a20efa-36fc-48d4-9050-133b6ccd38ab.png">

**Comment by gianmarco-motional** [comment]
Hi @IvanChen777!
Thanks for raising the issue. This has already been fixed in the v1.0 release, which should be merged soon.

Feel free to reopen if you have any follow up :slightly_smiling_face:
