### ISSUE TITLE
code version

### ISSUE THREAD

**Issue by wangjunhe8127** [motional/nuplan-devkit#143]
*Ex. What is a lane connector? or How many wheels do your vehicles have?*
Hi, I want to know, we should use which version when we train our model. is nuplan-devkit v1.0 or 0.6?
Thank you!

**Comment by patk-motional** [comment]
Hi @wangjunhe8127,

We have yet to release v1.0 as of this moment. For the time being, if you want to use branch v1.0 feel free to as your own risk. The branch may change soon as it is still a pull request.
