### ISSUE TITLE
simulation in test phase

### ISSUE THREAD

**Issue by wangjunhe8127** [motional/nuplan-devkit#145]
Ex.

**Comment by wangjunhe8127** [comment]
Ex. is the scenario's property in official test phase the same as the scenaros'property in training？
such as lidar_pc？

**Comment by patk-motional** [comment]
Hi @wangjunhe8127,

Can you clarify what you mean by "property"?

**Comment by wangjunhe8127** [comment]
> Hi @wangjunhe8127,
> 
> Can you clarify what you mean by "property"?

such as scenario_type？
