### ISSUE TITLE
which can we change？

### ISSUE THREAD

**Issue by wangjunhe8127** [motional/nuplan-devkit#147]
![image](https://user-images.githubusercontent.com/63217254/194715322-a866f8eb-1d53-4a57-b210-fbfe849ebc18.png)
which can we change in these？

**Comment by patk-motional** [comment]
Hi @wangjunhe8127,

For your own experimentation, you can change any of them. For the competition please refer to the competition [documentation](https://nuplan-devkit.readthedocs.io/en/latest/competition.html#challenges). You will not have control over the configuration of the simulation to ensure fairness
