### ISSUE TITLE
is always scenario.get_traffic_light_status_at_iteration(0)?

### ISSUE THREAD

**Issue by wangjunhe8127** [motional/nuplan-devkit#149]
![image](https://user-images.githubusercontent.com/63217254/194716807-95135323-bbb9-454b-9239-ce2d0200821b.png)
I want to comfire whether it is right.

**Comment by patk-motional** [comment]
Hi @wangjunhe8127,

You will only get the traffic light status at iteration 0 if you do this. I would recommend getting the iteration number from `PlannerInput`
