### ISSUE TITLE
Error in custom planner submission

### ISSUE THREAD

**Issue by Shi-Qi-Li** [motional/nuplan-devkit#151]
Hi, I met the following error when I changed the simple_planner to ml_planner in `nuplan/entrypoint_submission.sh` and run `docker-compose up --build` after built an docker image.
I wonder how to handle it.
![error](https://user-images.githubusercontent.com/29630040/194867350-6435274e-8cd5-4f0a-baa6-78b01b98a384.png)

**Comment by gianmarco-motional** [comment]
Hi @Shi-Qi-Li!

The instantiation of the ML planner should be 1-1 with what you run locally. You need to specify the `model_config` and `checkpoint_path`.

I think this should be present in the tutorials.

**Comment by bulbcult** [comment]
> Hi, I met the following error when I changed the simple_planner to ml_planner in `nuplan/entrypoint_submission.sh` and run `docker-compose up --build` after built an docker image. I wonder how to handle it. ![error](https://user-images.githubusercontent.com/29630040/194867350-6435274e-8cd5-4f0a-baa6-78b01b98a384.png)

Hi @Shi-Qi-Li , how did you set model_config in nuplan/entrypoint_submission.sh? 
just like this? model_config: urban_driver_open_loop_model

I tried this, but it doesn't work.
Thank u very much in advance!

**Comment by Shi-Qi-Li** [comment]
> > Hi, I met the following error when I changed the simple_planner to ml_planner in `nuplan/entrypoint_submission.sh` and run `docker-compose up --build` after built an docker image. I wonder how to handle it. ![error](https://user-images.githubusercontent.com/29630040/194867350-6435274e-8cd5-4f0a-baa6-78b01b98a384.png)
> 
> Hi @Shi-Qi-Li , how did you set `model_config` in `nuplan/entrypoint_submission.sh`? just like this? `model_config: urban_driver_open_loop_model ` I tried this, but it doesn't work. Thank u very much in advance!

Hi @bulbcult ,  I think this https://github.com/motional/nuplan-devkit/issues/284#issuecomment-1535798483 will help.
