### ISSUE TITLE
v0.6 nuboard cant display histograms or scenarios

### ISSUE THREAD

**Issue by Fan-Yixuan** [motional/nuplan-devkit#152]
I can only see evaluation scores in 'overview' of v0.6 nuboard. As for 'Histograms' and 'Scenarios', they are all empty. My environment is attached. Thanks a lot.
[py39.txt](https://github.com/motional/nuplan-devkit/files/9750914/py39.txt)
My command for simulation:
`python simulation_nuplan.py \
    +simulation=closed_loop_reactive_agentssimlat \
    planner=ml_planner \
    model=raster_model \
    scenario_builder=nuplan \
    scenario_filter=all_scenarios \
    scenario_filter.scenario_types="[near_multiple_vehicles, on_pickup_dropoff, starting_unprotected_cross_turn, high_magnitude_jerk]" \
    scenario_filter.num_scenarios_per_type=10 \
    planner.ml_planner.checkpoint_path=${CKPT_PATH} \`
After the simulation, my command for nuboard:
`python nuboard_nuplan.py \
    scenario_builder=nuplan \
    simulation_path="[/home/fanyx/AutoDrive/output/exp/simulation_closed_loop_reactive_agents/2022.10.11.11.24.25]"`

**Comment by JingyuQian** [comment]
Hi @Fan-Yixuan,
You need to click the cogwheel button on the top right corner to select scenarios for visualization. Hope this helps.

**Comment by Fan-Yixuan** [comment]
Hi @JingyuQian, Thanks a lot! my problem was solved perfectly, although it might be silly...

**Comment by JingyuQian** [comment]
Hi @BeautyCJ, sorry for the late reply. This is my nuboard screeshot. You can see the cogwheel button. (v0.2)
Don't know why there isn't one on your side... Maybe try cloning the repo as a fresh start?
![screenshot-20230106-154749](https://user-images.githubusercontent.com/13508878/211118389-f51bc527-17d1-49ce-965c-e20faf543eee.png)

**Comment by dmachapu** [comment]
Hi Together, I am stuck at the same problem, even though I select the scenario type using the cog wheel (I doubled checked that aggregator metrics are presents), No simulation data is shown. Any hints would be a great help.

**Comment by motata** [comment]
I'm facing the same problem. And there is no cogwheel on the top right corner. Anyone has a clue? Thanks.
