### ISSUE TITLE
Small dataset partitions

### ISSUE THREAD

**Issue by perone** [motional/nuplan-devkit#158]
Hi, thanks for sharing the dataset. Are there any plans to release a smaller version of it ? The nuplan-mini is too small and doesn't have standard train/val/test partitions, and the whole dataset is around ~1TB of data. Having a smaller dataset that is bigger than the mini but with standard train/val/test partitions can really help future research work/benchmarks/etc. Thanks !

**Comment by patk-motional** [comment]
Hi @perone,

The training split is already split into smaller chunks. You do not need to download the entire dataset.
![image](https://user-images.githubusercontent.com/95635553/195595451-a34185b8-46cc-4569-af8a-e04e41e3ba55.png)

Is this what you are looking for?

**Comment by perone** [comment]
Thanks @patk-motional. But if someone uses only a single city for example for training, it will have other unseen cities in the standard val/test splits, which means a change in expected generalization. Ideally it would have to be a resample of the training/val/test and also have a standard partitioning (that can be downloaded from nuPlan, otherwise if someone uses a custom training/val/test, it will be divergence from the standard benchmark partitions and will have to make it available elsewhere too).

**Comment by perone** [comment]
Thanks @patk-motional, I think 10% to 20% would be fine, but looking at the following table (from the website):
<img width="893" alt="image" src="https://user-images.githubusercontent.com/412328/195638282-008ab878-4a6a-45f1-b7fb-8bb83e639e36.png">
It is not clear if the hours counted there include or not the val/test splits or if it is only training data.

**Comment by richie-live** [comment]
@perone 

> Hi, thanks for sharing the dataset. Are there any plans to release a smaller version of it ? The nuplan-mini is too small and doesn't have standard train/val/test partitions, and the whole dataset is around ~1TB of data. Having a smaller dataset that is bigger than the mini but with standard train/val/test partitions can really help future research work/benchmarks/etc. Thanks !

Hi, have you found a way to adrress this problem?
