### ISSUE TITLE
Can you extend the competition deadline?

### ISSUE THREAD

**Issue by mh0797** [motional/nuplan-devkit#159]
Hello,
I am a PhD student and would very much like to participate in the upcoming nuPlan competition. For this I have several promising approaches. Unfortunately, I will probably not be able to make it in time before the deadline, since caching, training and simulation are time-consuming.

Also, judging from current open github issues, there are many developers and researchers out there that are currently gaining traction in nuPlan, but will probably not be able to make a submission before the deadline, especially regarding the open issues concerning the simulation. With that said, I suppose the number of submissions and thereby the relevance of the challenge could be increased by giving them the opportunity to participate as well.

Therefore I would like to kindly ask you to consider extending the deadline for the competition.

**Comment by mh0797** [comment]
I just saw, you announced that the competition will be postponed to 2023.
Therefore I assume that the challenge will be based on devkit-1.0 ?

**Comment by patk-motional** [comment]
Hi @mh0797,

Indeed we have seen an uptick in interest in the past weeks. We will make have a few more releases before the competition start. Most of the interfaces will stay the same. We will still be making bug fixes as needed.

Thanks for your interest in the competition.
