### ISSUE TITLE
Training speed drops greatly when using a larger dataset

### ISSUE THREAD

**Issue by lw-2018** [motional/nuplan-devkit#16]
Hi,
I am trying to train the raster model with nuplan_v0.2, I found the training speed drops greatly when using a larger dataset.

**4.67it/s** with limit_scenarios_per_type=0.001
**4.53s/it** with limit_scenarios_per_type=0.1

its my training command
`CUDA_VISIBLE_DEVICES=1 python nuplan/planning/script/run_training.py \
    experiment_name=raster_experiment_01 \
    py_func=train \
    +training=training_raster_model \
    scenario_builder=nuplan \
    scenario_builder.nuplan.scenario_filter.limit_scenarios_per_type=0.1 \
    scenario_builder.nuplan.scenario_filter.subsample_ratio=0.01 \
    lightning.trainer.params.max_epochs=10 \
    data_loader.params.batch_size=64 \
    data_loader.params.num_workers=32`

**Comment by bradyz** [comment]
It could be possible that for `limit_scenarios_per_type=0.001`, you have already seen all the samples and cached all the features,
and for `limit_scenarios_per_type=0.1`, the data workers are seeing new samples and takes more time to create/cache the raster feature.

Take a look at the `cache_data` function in `run_training.py`  and consider running this before actually training

**Comment by lw-2018** [comment]
I solved this problem by running the `cache_data` first, thanks for the help. @bradyz
