### ISSUE TITLE
Error in Trajectories Feature Deserialization 

### ISSUE THREAD

**Issue by mh0797** [motional/nuplan-devkit#160]
### Steps To Reproduce
Run the following test script
```
from nuplan.planning.training.preprocessing.features.trajectories import Trajectories
from nuplan.planning.training.preprocessing.features.trajectory import Trajectory
import numpy as np

single_trajectory = Trajectory(data=np.ones([2,5,3]))
trajectories_feature = Trajectories.deserialize(Trajectories([single_trajectory, single_trajectory ]).serialize())
print(type(trajectories_feature.trajectories[0]))
```
### Problem
the printed type should be Trajectory but is dict

### Additional context
In order to fix this, l.31 has to be changed from `return Trajectories(trajectories=data["trajectories"])` to `return Trajectories(trajectories=[Trajectory.deserialize(t) for t in data["trajectories"]])`

**Comment by michael-motional** [comment]
Good catch! The fix will be included in the upcoming release (and soon we'll have a more flexible release process)
