### ISSUE TITLE
Does data augmentation overwrite the cache?

### ISSUE THREAD

**Issue by mh0797** [motional/nuplan-devkit#164]
Hi, 

Assume I have cached a dataset for a model. The caching was done without data augmentation.
If I then train a model with data augmentation using this cache-dir, will this overwrite the cache, so that if i afterwards want to train yet another model without data augmentation, i would have to re-cache the dataset?

**Comment by christopher-motional** [comment]
Hi @mh0797, sorry for the delayed response. No, training with data augmentation with pre-cached features should not overwrite the cache you've created, so you should be free to run as many jobs as you want with different augmentation parameters or without entirely without re-caching
