### ISSUE TITLE
Question about planner parameter in nuplan_framework.ipynb

### ISSUE THREAD

**Issue by IvanChen777** [motional/nuplan-devkit#169]
Hi, I have a question about ml_planner, when I run the prepare the simulation config section, first I put the planner config as simple_planner, it works well. However, when I want to change it into ml_planner, it has following mistake:
<img width="1144" alt="截屏2022-10-22 13 51 13" src="https://user-images.githubusercontent.com/91310432/197337441-0e7514c9-7b58-4c3c-83ef-1682e5b2a327.png">
Does someone knows this issue? Thank you in advance:)

**Comment by christopher-motional** [comment]
Hi @IvanChen777,

What was the command you used to run simulations? After setting the planner to ml_planner did you set the model using `model=<MODEL_NAME (i.e. raster_model)>` along with setting `planner.ml_planner.model_config=${model}`?

**Comment by IvanChen777** [comment]
Hi, @christopher-motional , thank you for your advice, this is the issue I met:)

**Comment by christopher-motional** [comment]
Glad it's working now!
