### ISSUE TITLE
Is there any way to export the video of "scenario"-"simulation" in nuboard?

### ISSUE THREAD

**Issue by HeYDwane3** [motional/nuplan-devkit#17]
Hi NuPlan team,

I am playing with the NuBoard with my trained & simulated results. 

It seems that in the "Scenario" part, we have to drag and move the "frame" to see the "simulation" results, I am wondering is there any way wo can export the video directly?

Thanks

**Comment by kokseang-motional** [comment]
hi @HeYDwane3 
Thanks for the suggestion, it is a nice feature that we should have. Unfortunately, we dont have any way to export the video directly, but we are working on it now,

**Comment by kokseang-motional** [comment]
Will close the issue for now.

**Comment by cisimon7** [comment]
Just checking if there's any update on this?

**Comment by NishkaArora** [comment]
Was this feature added yet?
