### ISSUE TITLE
OperationalError: no such table: lidar_pc

### ISSUE THREAD

**Issue by IvanChen777** [motional/nuplan-devkit#174]
Hi, when I try the dataset v1.1, I met this problem in nuplan_framework.ipynb tutorial as well as nuplan_framework_tutorial.ipynb, does anyone knows this issue? If so, please tell me. Thank you very much:)
<img width="1327" alt="截屏2022-10-29 07 54 38" src="https://user-images.githubusercontent.com/91310432/198816261-42f23093-8b41-4aa4-b449-202037a79ea9.png">

**Comment by IvanChen777** [comment]
Or does someone knows where this lidar_pc should be, I thought that it is because I forgot to install something in dataset of v1.1, however, I think that I follow the instruction of dataset setup, then I am kind of lost...

**Comment by Curtainzsl** [comment]
I also meet this question. Could you find the point could in the dataset.

**Comment by BUXINYI** [comment]
> 或者有人知道这个lidar_pc应该在哪里，我以为是因为我忘记在 v1.1 的数据集中安装一些东西，但是，我想我按照数据集设置的说明进行作，然后我有点迷路了......

我也遇到了这个问题，请问你解决了吗

**Comment by BUXINYI** [comment]
> 我也遇到这个问题。你能在数据集中找到点吗？
请问你解决了这个问题了吗
