### ISSUE TITLE
Question about training command in terminal

### ISSUE THREAD

**Issue by IvanChen777** [motional/nuplan-devkit#176]
Hi, I have a question about training command in nuplan_framework.ipynb. When I use the command provided by nuplan_framework.ipynb in terminal, it seems that I can run it successfully in v1.0, however, after I update the file into v1.1, I met an issue, RuntimeError: stack expects each tensor to be equal size, but got [16, 3] at entry 0 and [12, 3] at entry 3, which happens during the training. Do you think that it is because the size of some data in this dataset is different? Thanks.
<img width="990" alt="截屏2022-11-04 08 40 46" src="https://user-images.githubusercontent.com/91310432/199918961-28743b8c-d4ed-4439-a8f9-6d9ca4ff8c45.png">

**Comment by JingyuQian** [comment]
If you're using cached data, note that the old target is 12 points with 0.5s interval, totaling 6s prediction; But the new target is 16 points totaling 8s prediction. 
It is very likely your cached data contains both of these, so they cannot be stacked together.

**Comment by IvanChen777** [comment]
Thank you for your reply! I have a better understanding about this error. However, when I check my mini data, it is from nuplan v1.1 dataset mini split, I download the dataset from here. Then I retrain my model again, the result is still the same, do you have some suggestions about this issue?

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/91310432/203020335-8aa19dfc-c162-4d4f-906f-61c9a096fbd2.png">

**Comment by gianmarco-motional** [comment]
The horizon should be a parameter during training, it does not come from the database version. One problem could be that the cache is not invalidated correctly, could you check that? @christopher-motional FYI

**Comment by IvanChen777** [comment]
> The horizon should be a parameter during training, it does not come from the database version. One problem could be that the cache is not invalidated correctly, could you check that? @christopher-motional FYI

For the mini data, I don't know if it is working now, but for the training and validation, I could train them in the terminal by command now
