### ISSUE TITLE
scenario tags

### ISSUE THREAD

**Issue by anran1231** [motional/nuplan-devkit#18]
Thanks for your fantastic work. It is said in the nuplan paper, that to enable scenario-based metrics, we automatically annotate intervals with tags for complex scenarios. I am very curious about the way you label scenarios automatically. Is it also possible for you to share the  scenario labelling tools?

**Comment by muety** [comment]
I'd also love to learn more about how you went about mining those rare scenarios and how your offline mining tool works under the hood! Is there any further technical information available anywhere?
