### ISSUE TITLE
Tutorial bug in "Prepare the training config" in nuplan_framework.ipynb

### ISSUE THREAD

**Issue by BeautyCJ** [motional/nuplan-devkit#187]
### Describe the bug
I run this in notebook it goes wrong. while i run in common line it works well
and i don't know how to specify the value for splitter

![image](https://user-images.githubusercontent.com/11649149/202961721-4cc68c53-3ebb-4257-a27c-21d096488725.png)

**Comment by CrisCloseTheDoor** [comment]
try to use
```
'splitter=nuplan'
```

**Comment by BeautyCJ** [comment]
There are still problems

![image](https://user-images.githubusercontent.com/11649149/202984271-cf9a97a4-3980-4615-b1aa-8607615b49da.png)

**Comment by BeautyCJ** [comment]
Yes! I have installed with no error. And I can run run it in common line and it works well~ 
Later, I basically use the command line mode to perform training. I will ignore this problem first, but thank you for your reply

**Comment by BeautyCJ** [comment]
> Might be a silly suggestion but: have you installed your local copy of nuplan-devkit with `pip install -e .`?

YES! I reinstall the nuplan-devkit, it works fine!!! Thanks a lot!!!

**Comment by balckwell** [comment]
it is an excellent advice !!!
