### ISSUE TITLE
Question about applying trainval data rather than mini data

### ISSUE THREAD

**Issue by IvanChen777** [motional/nuplan-devkit#188]
Hi, I have a question about using trainval data rather than mini data, that is, the folder structure of trainval in the dataset setup seems that all the db files, no matter the training or validation data are put in the same folder, however, when I try to download the trainval dataset, the folder structure is like the second picture(train_boston val), so my question is, should I put the db file of both structure together under the trainval folder? Thank you!
<img width="723" alt="截屏2022-11-21 11 13 19" src="https://user-images.githubusercontent.com/91310432/203024545-9ccdbb66-7ed1-462c-893d-8a4290288e6c.png">
<img width="126" alt="截屏2022-11-21 11 16 20" src="https://user-images.githubusercontent.com/91310432/203025085-d995cf86-1900-4b5a-9e1c-889c9c548f18.png">

**Comment by patk-motional** [comment]
Hi @IvanChen777, 

Yes, that would work. It is up to how you set specify in the scenario filter which maps you want to include
