### ISSUE TITLE
nuboard cant display histograms or scenarios

### ISSUE THREAD

**Issue by BeautyCJ** [motional/nuplan-devkit#189]
I download the newest version of code，and i see the version of nuboard is v0.2, please tell me is it correct.

and  i meet the same question as mentioned in https://github.com/motional/nuplan-devkit/issues/152

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/11649149/203308479-0b47b51a-5fdf-408f-b098-d864999836c7.png">

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/11649149/203308577-b9c7a553-2a67-424a-8a91-0d226dea27a3.png">

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/11649149/203308686-8e006483-7d7b-4331-a29e-fffe3996432d.png">

**Comment by BeautyCJ** [comment]
@gianmarco-motional ~

**Comment by gianmarco-motional** [comment]
Could you send the exact command to reproduce your results? (Both command for running the simulation and displaying nuboard)

**Comment by BeautyCJ** [comment]
Yes, here are my commond:

path1="output/exp/simulation_open_loop_boxes/2022.11.22.18.43.56"
python nuplan/planning/script/run_nuboard.py simulation_path="[$path1]"

**Comment by yaqlee** [comment]
have you solved the problem? I'm waiting for answers.

**Comment by rossgreer** [comment]
Have you clicked the cog wheel in the top right corner, @yaqlee ? 
This fixed it for me.

**Comment by motata** [comment]
I've met the same problem here. v0.2 nuboard doesn't show a cogwheel in the top right corner.
