### ISSUE TITLE
how to simulate in the command line

### ISSUE THREAD

**Issue by BeautyCJ** [motional/nuplan-devkit#191]
I can run the simulation script with ml_planner in the tutorial notebook, but I don't know how to run this in the command line since I am not familiar with hydra.  I hope you can help me, thank you very much~

cfg = hydra.compose(config_name=CONFIG_NAME, overrides=[
    f'experiment_name={EXPERIMENT}',
    f'group={SAVE_DIR}',
    'planner=ml_planner',
    'model=raster_model',
    'planner.ml_planner.model_config=${model}',  # hydra notation to select model config
    f'planner.ml_planner.checkpoint_path={MODEL_PATH}',  # this path can be replaced by the checkpoint of the model trained in the previous section
    f'+simulation={CHALLENGE}',
    *DATASET_PARAMS,
])

**Comment by CrisCloseTheDoor** [comment]
If you run in command, you should use quotation marks "" on params for hydra to read, like:
```
python run_simulation.py 
'+simulation=closed_loop_reactive_agents' \
'number_of_cpus_used_for_one_simulation=null' \
'experiment_name=simulation_vector_experiment' \
'metric_aggregator=default_weighted_average' \
'scenario_builder=nuplan_mini' \
'scenario_filter=all_scenarios' \
'scenario_filter.num_scenarios_per_type=10' \
'planner=ml_planner' \
'model=vector_model' \
'worker=ray_distributed' \
'planner.ml_planner.model_config=${model}' \
'planner.ml_planner.checkpoint_path= ***** \
```

**Comment by BeautyCJ** [comment]
It works for me, Thank you very much !!!
