### ISSUE TITLE
Scenario mapping

### ISSUE THREAD

**Issue by cfcv** [motional/nuplan-devkit#195]
Hi,

I was checking the configuration files for training and the scenario_mapping got my attention (nuplan_scenario_mapping.yaml), it defines  a mapping from scenario type and scenario duration + extraction offset. All of the scenario types have a [15.0, -3.0], so if I understand correctly it means that we will take a 15s window and the ego position will start at 3s before the trigger event occurred.

So it means that when training, the network will always sees samples where the Ego is at 3s before the event?

BTW: I am trying to vary the configuration of the scenario mapping duration and extraction offset in the nuplan_scenario_mapping.yaml. But when visualizing the samples, I don't see any difference. That's why I am interested in understending how the scenario mapping works  (when lunch training I set the flag cache.force_feature_computation to True to make sure the features are recomputed after the change in the configuration file).

Thanks in advance.

**Comment by patk-motional** [comment]
@cfcv,

Your interpretation is correct of Scenario mapping is correct. However, it is only used for simulation, not training. You will only see a difference when you generate the simulation. Let me know if you have any more questions feel free to ask. I will close this issue for now.

**Comment by cfcv** [comment]
Thanks for the clarification Pat!
