### ISSUE TITLE
Can I make scenario tags?

### ISSUE THREAD

**Issue by polcomicepute** [motional/nuplan-devkit#199]
Is there a way for users to create their own scenario tags?
If so, how can I create my own scenario tags?
If not, could you provide the function later?

And when will the raw sensor data such as images and lidar point clouds be available?

Thank you for providing an excellent planning dataset.

**Comment by patk-motional** [comment]
Hi @polcomicepute,

You cannot create your own scenario tags. The [tags](https://nuplan-devkit.readthedocs.io/en/latest/nuplan_schema.html#scenario-tag) are baked into the database. Unfortunately, this functionality will not be supported in the future.

The sensor data will be released Q1 of next year.

**Comment by muety** [comment]
I was wondering whether the code you used to tag the scenarios (mostly rule-based, I'd assume?) is available somewhere? Would be super useful for me to have!

**Comment by patk-motional** [comment]
Hi @muety,

It is all rules-based. We cannot share that code with you, unfortunately.

**Comment by SaraMo14** [comment]
Hi @patk-motional,

In the scenario descriptions there are some thresholds for the rule-based approach you were talking about. Is it possible to have more information about them? 
![image](https://github.com/user-attachments/assets/d279f6fc-0f35-41a0-8abb-b088657f723b)

**Comment by rdesc** [comment]
@SaraMo14 do you mind sharing a link to that table that you took a screenshot of?
