### ISSUE TITLE
About the dataset structure & tutorial.

### ISSUE THREAD

**Issue by knifeven** [motional/nuplan-devkit#200]
Hi. 
I wonder about the dataset structure
I can download them about v1.1 via https://www.nuscenes.org/nuplan#code
 - Maps 1ea
 - Mini Split 1ea
 - Train Split 8ea
   boston 1 / pittsburgh 1 / Las vegas 6
 - val split 1ea
 - test split 1ea

With https://nuplan-devkit.readthedocs.io/en/latest/dataset_setup.html, the structure  is explained, but I couldn't follow it exactly with downloaed files.

What is the exp?
What is the trainval?

Also I tried to run some tutorial.
But when "nuplan_scenario_visualization.ipynb" run, it failed.
--------------------------------------------------------------------------------------------------
File /mnt/nuplan/nuplan-devkit/nuplan/database/nuplan_db/query_session.py:21, in execute_many(query_text, query_parameters, db_file)
     18 cursor = connection.cursor()
     20 try:
---> 21     cursor.execute(query_text, query_parameters)
     23     for row in cursor:
     24         yield row

OperationalError: near "NULLS": syntax error
------------------------------------------------------------------------------------------------

Could you help me about the problem I got?

**Comment by alchemz** [comment]
@knifeven Thanks for posting the clarification questions. Have you found where is the 10% raw sensor data?

**Comment by knifeven** [comment]
@alchemz Thanks for your quick reply. I wonder what the 10% raw sensor data is.
Could you guide me more detail?

**Comment by knifeven** [comment]
@alchemz

**Comment by knifeven** [comment]
@alchemz 
Hi, I will wait for your reply. thx.!

**Comment by alchemz** [comment]
@knifeven Excuse me for the delayed response. The nuplan dataset should not only contain motion datasets, but also senor datasets as lidar, imaginary etc. I have been looking into if the new release includes the sensor data. 

Just confirmed it. The sensor data is not included in this release.

**Comment by knifeven** [comment]
@alchemz Thx for your reply. 
Then, how can I run "nuplan_scenario_visualization.ipynb" and other thing?
Could you inform me the release date of sensor data?

**Comment by alchemz** [comment]
@knifeven You can run nuplan_scenario_visualization.ipynb perfectly fine without the sensor data. The notebook is meant to visualize the motion dataset, does not use raw sensor data at all.

I have tested it on my end. The nuplan_scenario_visualization.ipynb works on my local machine with nuplan dataset.

**Comment by knifeven** [comment]
@alchemz I got it.
I already asked my problem about running nuplan_scenario_visualization.ipynb
Do you have any idea about it?

--------------------------------------------------------------------------------------------------------------------------------
But when "nuplan_scenario_visualization.ipynb" run, it failed.
File /mnt/nuplan/nuplan-devkit/nuplan/database/nuplan_db/query_session.py:21, in execute_many(query_text, query_parameters, db_file)
18 cursor = connection.cursor()
20 try:
---> 21 cursor.execute(query_text, query_parameters)
23 for row in cursor:
24 yield row

OperationalError: near "NULLS": syntax error
---------------------------------------------------------------------------------------------------------------------------------

**Comment by knifeven** [comment]
@alchemz 
I solved it.
the sqlite3 version was 3.22, and I upgraded it to 3.31.
It works!
Thanks.

**Comment by EoinKenny** [comment]
What about the trainval and exp folders? I also don't understand how to set that up? Thanks!
