### ISSUE TITLE
simulation history buffer is shorter than expected

### ISSUE THREAD

**Issue by mh0797** [motional/nuplan-devkit#205]
### Describe the bug
In the challenge announcement it is stated that the past observation horizon is 2.0s. Also, in the `default_simulation.yaml` config, the simulation history buffer duration is set to 2.0 seconds. Thereby I would assume, that a planner can use up to 2.0s of past observations in simulation. However, calculating features from simulation using a `past_trajectory_sampling` with a `time_horizon` of 2.0s is not possible, as the actually available history is slightly below 2.0s (depending on the scenario between 1.99s and 1.90s). In consequence, simulation will fail as the past trajectory exceeds the available history.

### Steps To Reproduce
1. Run a simulation setting `past_trajectory_sampling.time_horizon=2.0`

**Comment by patk-motional** [comment]
Addressed in https://github.com/motional/nuplan-devkit/issues/206#issuecomment-1378502682
