### ISSUE TITLE
Why is ego velocity_y much more smaller than ego_velocity_x

### ISSUE THREAD

**Issue by alantes** [motional/nuplan-devkit#209]
Hello, developers! Thank you for your data and dev-kit!

In "2021.10.15.02.36.56_veh-53_02020_02442.db" of Singapore split, the ego vehicle ran a route like this:
![image](https://user-images.githubusercontent.com/13460765/209908498-7937e6a7-40b7-4cb3-83c3-10b84a43f91b.png)

But the corresponding velocity_x among the way is like:
![image](https://user-images.githubusercontent.com/13460765/209908591-4ae8af30-6daa-4066-b440-f564c0ee6c78.png)

While the velocity_y is like:
![image](https://user-images.githubusercontent.com/13460765/209908680-8179a39a-f545-4cbf-a92a-329769fa59ea.png)

To me, velocity_y is like noise rather than normal speed.

Here is my code:
```python
velocity_x = []
velocity_y = []
for i in range(len(scenarios_list)):
    scenario = get_default_scenario_from_token(
        NUPLAN_DATA_ROOT, log_db, scenarios_list[i]["token"].hex(), NUPLAN_MAPS_ROOT, NUPLAN_MAP_VERSION
    )
    velocity_x.append(scenario.initial_ego_state.agent.velocity.x)
    velocity_y.append(scenario.initial_ego_state.agent.velocity.y)
```

**Comment by alantes** [comment]
If I calculate velocity by magnitude and heading, the graphs seem much more correct:
```python
import numpy as np
velocity_x = []
velocity_y = []
for i in range(len(scenarios_list)):
    scenario = get_default_scenario_from_token(
        NUPLAN_DATA_ROOT, log_db, scenarios_list[i]["token"].hex(), NUPLAN_MAPS_ROOT, NUPLAN_MAP_VERSION
    )
    heading = scenario.initial_ego_state.rear_axle.heading
    velocity = scenario.initial_ego_state.dynamic_car_state.rear_axle_velocity_2d.magnitude()
    # velocity_x.append(scenario.initial_ego_state.dynamic_car_state.center_acceleration_2d.x)
    # velocity_y.append(scenario.initial_ego_state.dynamic_car_state.center_acceleration_2d.y)
    velocity_x.append(velocity * np.cos(heading))
    velocity_y.append(velocity * np.sin(heading))
```
v_x:
![image](https://user-images.githubusercontent.com/13460765/209910885-224b6e49-284f-4a07-9489-46d1611472c7.png)

v_y:
![image](https://user-images.githubusercontent.com/13460765/209910928-bbc12330-ee98-48f0-a1d7-301d7932f59d.png)

**Comment by patk-motional** [comment]
Hi @alantes, 

Sorry for the delay. The reason that the velocity_y is small is that the velocities are in the ego's frame. velocity_x is the longitudinal direction and velocity_y is the lateral direction. Hope this clears up some of your confusions
