### ISSUE TITLE
Closed-loop training

### ISSUE THREAD

**Issue by gbartyzel** [motional/nuplan-devkit#216]
Hello,

Is there possible to implement a closed-loop training with nuplan-devkit, like the one implemented here https://github.com/woven-planet/l5kit/blob/master/l5kit/l5kit/planning/vectorized/closed_loop_model.py? I need a closed-loop training for the [MGAIL](https://arxiv.org/abs/2210.09539) algorithm. 
I would be grateful for any suggestions!

**Comment by patk-motional** [comment]
Hi @gbartyzel,

We do not have plans to introduce closed-loop training in the near future. Sorry for the inconvenience
