### ISSUE TITLE
How to get boundary type/Laneline type?

### ISSUE THREAD

**Issue by QuanyiLi** [motional/nuplan-devkit#219]
Hi,

I would like to know how to get the boundary type like broken lines, continuous lines, yellow lines, and so on. It would be helpful for detecting if the car crosses the yellow line or not, which should be prohibited in our daily life.  Also, this can be a termination condition, I think.

**Comment by QuanyiLi** [comment]
I found that the boundary type can be retrieved from```boundary_type_fid```. For example, ```2``` is for the continuous line, and ```0``` is for the broken one. But I can not understand the meaning of other digits, like ```3```, and not pretty sure about the meaning of ```0``` and ```2```, lol

**Comment by patk-motional** [comment]
Hi @QuanyiLi,

Here is the meaning behind the labels:

0 - "LaneDivider" = Lane Divider
1 - Unused
2 - "Roadside" = Roadside boundary
3 - "Virtual" = A virtual boundary is generally used for lane_connectors where the boundaries are not marked by physical markings

Hope that helps

**Comment by dongb5** [comment]
@QuanyiLi Hi, how did you get the boudnar_type_fid? I cannot find them

**Comment by QuanyiLi** [comment]
I checked my legacy code. It may be something like this:
```
line_type = get_line_type(int(boundaries.loc[[str(left.id)]]["boundary_type_fid"]))
```
This line is from:

https://github.com/metadriverse/scenarionet/blob/46747d85aa3f2284b0a66ce73149c671986d2eb1/scenarionet/converter/nuplan/utils.py#L245

where you can find more context.
