### ISSUE TITLE
Routing utilities in map api

### ISSUE THREAD

**Issue by StefanoS90** [motional/nuplan-devkit#22]
Hi!

I believe that one big potentiality of nu-plan is to allow to compare ML base planners vs classical planners.
In order to do so, it would be great to be able to easily plug classical planners in the framework that usually makes big use of the HD map and lanes connectivity.

Looking at the map api, i did not  find any routing utilities, that allow to query the HD map conditioned to the 'mission goal' of the ego car. For example it would be nice to have functions that returns the shortest lanes sequence that leads to the goal or the available lane changes compliant with the mission goal etc... (similar to what is done in the Lanelet2 routing api https://github.com/fzi-forschungszentrum-informatik/Lanelet2/tree/master/lanelet2_routing).

Do you plan to extend the functionalities of the map api in this sense?
Thanks!

**Comment by juraj-motional** [comment]
Hi @StefanoS90,

thanks for your idea, you are entirely right! We hope people will try their classical planners as well. 

Yes, in the next release, we plan to include a sequence of lanes or a sequence of roadblocks for every scenario into the dataset. So you will know precisely which route your planner should take. Please let us know whether that will help with your use case.
