### ISSUE TITLE
how can i get the goal states

### ISSUE THREAD

**Issue by wangjunhe8127** [motional/nuplan-devkit#221]
hi，i want to get the goal state, and i want to know which function will provide to me in test phase?
![image](https://user-images.githubusercontent.com/63217254/217211619-272a9bc2-f0d2-4ce1-af75-b5a4be31e2f8.png)

or there are other function to get the goal states?
thanks!

**Comment by patk-motional** [comment]
Hi @wangjunhe8127,

The mission goal will be given. However, you will be given this through the [PlannerInput](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/simulation/planner/abstract_planner.py#L29) class and not through the scenario interface directly

**Comment by yaqlee** [comment]
But PlannerInput class does not have property like 'goal state', how does it work?

**Comment by patk-motional** [comment]
This may have changed recently. Please check [PlannerInitialization](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/simulation/planner/abstract_planner.py#L18) instead. This will be given to your planner at the start of each scenario simulation .
