### ISSUE TITLE
What is the nature of `vx`, `vy`, `ax`, `ay` in ego and agents?

### ISSUE THREAD

**Issue by PieroMacaluso** [motional/nuplan-devkit#227]
Hello everyone! 👋🏼 
Unfortunately I am writing this question as I have not been able to find any documentation on this.
I am wondering if the variables `vx`, `vy`, `ax`, `ay` that we can find in the state of agents and ego vehicles (after normalising the scene) are values with respect to the Cartesian plane or if the `x`s are longitudinal and `y`s lateral velocity and acceleration respectively.

In particular, I refer to the following functions (as an example)

https://github.com/motional/nuplan-devkit/blob/630f9d32a4b23f1b414ba6f4c26b9d4b539dcc62/nuplan/planning/training/preprocessing/utils/agents_preprocessing.py#L857-L889

https://github.com/motional/nuplan-devkit/blob/630f9d32a4b23f1b414ba6f4c26b9d4b539dcc62/nuplan/planning/training/preprocessing/utils/agents_preprocessing.py#L779-L792

I think this should be clarified in the docs as it can be very useful to know which operation to apply to normalise / transform these elements.

**Comment by patk-motional** [comment]
Hi @PieroMacaluso,

The agent pose velocities are in the global frame
The ego pose is in the global frame while velocities are in the local frame. We will update the documentation with these clarifications
