### ISSUE TITLE
run tutorials <nuplan_advanced_model_training.ipynb> - impot <NuPlanDBWrapper> meet bug

### ISSUE THREAD

**Issue by betterqiang** [motional/nuplan-devkit#228]
display:
    _allow unmapped _

how to solve:   SQLAlchemy  version to high (my version is 2.0.1)

need  to install   SQLAlchemy==1.4.27

----------------------------------------------------------------------------------------------------------------------
I'm so angry. It took a lot of time to find problems.
I hope the author can change SQLAlchemy>=1.4.27  to SQLAlchemy==1.4.27 in requirements.
over.

**Comment by BONGYOUNG** [comment]
Hello,
I'm having a same error.

I tried to reinstall with SQLAlchemy==1.4.27.
but it still makes error.
![Screenshot from 2023-02-16 15-12-23](https://user-images.githubusercontent.com/52023003/219283329-386ee962-105b-45c1-b14f-3301704b2fbe.png)

help me
