### ISSUE TITLE
download link without raw sensor blobs

### ISSUE THREAD

**Issue by bradyz** [motional/nuplan-devkit#23]
are there any plans to release a dataset with only annotations and no raw lidar points?

edit:
I had assumed the nuplan `.db` file was large (500 gb) because it included raw lidar data -
now I realize this is not the case (can someone confirm?)

**Comment by holger-motional** [comment]
Hi. Your edit is correct. The metadata and annotations of the nuPlan teaser are 500GB. For the full release it will be approx. 4TB. The sensor data is many orders of magnitude bigger, which is why we will only release 10% of the sensor data and only on AWS, not as download in the browser.
