### ISSUE TITLE
Can we use External Datasets/Simulators for the challenge? 

### ISSUE THREAD

**Issue by Yihanhu** [motional/nuplan-devkit#231]
As for the competition, can we use external datasets or simulator, i.e. Waymo Dataset or CARLA?

**Comment by patk-motional** [comment]
Hi @Yihanhu,

Let me speak with the team to discuss this. Will get back to you shortly

**Comment by patk-motional** [comment]
Hi @Yihanhu,

After a brief discussion, we concluded that you may use external datasets and simulator to test and train your models

**Comment by Dhagash4** [comment]
Hi @Yihanhu , I am also planning to train on other datasets and use their simulator? Can you tell how the setup would look like then?
