### ISSUE TITLE
Question about Competition Timeline

### ISSUE THREAD

**Issue by Jeff09** [motional/nuplan-devkit#232]
Hi, 

Thank you for hosting such a exciting challenge. I have saw there're two different timelines for the competition through two different website. I wonder which is the correct timeline. 

The first one is from[ nuPlan Planning Challenge ](https://nuplan-devkit.readthedocs.io/en/latest/competition.html). Here's the screenshot. 
<img width="728" alt="image" src="https://user-images.githubusercontent.com/13411170/222608300-507b952b-e797-47c7-975f-36966b04daf6.png">
It looks the competition is already started and the test phase is opening. And the competition closes at May 18th 2023. 

However, there is another timeline from [New Advances On Autonomous Driving](https://opendrivelab.com/event/cvpr23_ADworkshop) workshop at CVPR 2023. Here's the screenshot. 
![image](https://user-images.githubusercontent.com/13411170/222611999-e305d2f2-798d-4a6d-9bc6-8f83a4332e04.png)
It said the test server will open at 15 March 2023 and the deadline isn't clear yet. 

Please help me clarify which one is correct.

**Comment by patk-motional** [comment]
Hi @Jeff09,

The most up-to-date deadlines are according to https://nuplan-devkit.readthedocs.io/en/latest/competition.html.

- January 30th, 2023 - Warm-up phase and Test phase opens for submission
- May 18th, 2023 - Competition closes
- May 19th, 2023 - Finalists are announced and invited to share their code with us for verification
- June 2th, 2023 - Winners are announced
- June 18th, 2023 - The competition results are presented at the [New Advances On Autonomous Driving](https://opendrivelab.com/event/cvpr23_ADworkshop) workshop at CVPR 2023

Thank you for notifying us of the discrepancies. We will fix it asap

**Comment by patk-motional** [comment]
We have updated the competition deadlines:

- January 30th, 2023 - Warm-up phase and Test phase open for submission
- **May 26th, 2023 - Competition closes** - Finalists are announced and invited to share their code with us for verification
- June 2th, 2023 - Winners are announced
- June 18th, 2023 - The competition results are presented at the [New Advances On Autonomous Driving](https://opendrivelab.com/event/cvpr23_ADworkshop) workshop at CVPR 2023
