### ISSUE TITLE
tensorboard launching issue and 'ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by ankithadam** [motional/nuplan-devkit#244]
### Issue 1: 
I have run the jupyter notebook in conda nuplan env and has run the tutorial as per instruction but while launching tensorboard for visualizing training artifacts I am getting the error as shown in screenshot below:

### The code which I have used until now:
```
# Location of path with all training configs
CONFIG_PATH = '../nuplan/nuplan/planning/script/config/training'
CONFIG_NAME = 'default_training'

# Create a temporary directory to store the cache and experiment artifacts
SAVE_DIR = Path(tempfile.gettempdir()) / 'tutorial_nuplan_framework'  # optionally replace with persistent dir
EXPERIMENT = 'training_raster_experiment'
JOB_NAME = 'train_default_raster'
LOG_DIR = str(SAVE_DIR / EXPERIMENT / JOB_NAME)

# Initialize configuration management system
hydra.core.global_hydra.GlobalHydra.instance().clear()
hydra.initialize(config_path=CONFIG_PATH)

# Compose the configuration
cfg = hydra.compose(config_name=CONFIG_NAME, overrides=[
    f'group={str(SAVE_DIR)}',
    f'cache.cache_path={str(SAVE_DIR)}/cache',
    f'experiment_name={EXPERIMENT}',
    f'job_name={JOB_NAME}',
    'py_func=train',
    '+training=training_raster_model',  # raster model that consumes ego, agents and map raster layers and regresses the ego's trajectory
    'scenario_builder=nuplan_mini',  # use nuplan mini database
    'scenario_filter.limit_total_scenarios=500',  # Choose 500 scenarios to train with
    'lightning.trainer.params.accelerator=ddp_spawn',  # ddp is not allowed in interactive environment, using ddp_spawn instead - this can bottleneck the data pipeline, it is recommended to run training outside the notebook
    'lightning.trainer.params.max_epochs=10',
    'data_loader.params.batch_size=8',
    'data_loader.params.num_workers=8',
])
```
and the follow up code for launch:

```
%load_ext tensorboard
%tensorboard --logdir {LOG_DIR}
```
### Screenshot showing error:
![image_2023-03-19_133557236](https://user-images.githubusercontent.com/126139315/226162011-98f60a02-6759-4783-997e-59adef68da1f.png)

### Issue 2: 
After the tensorboard is not launching, I tried the next part of the tutorial "Launch training (within the notebook)"

The following is code that was run:

### Setup
```
from nuplan.planning.script.run_training import main as main_train

# Run the training loop, optionally inspect training artifacts through tensorboard (above cell)
main_train(cfg)
```
### Error generated:
```
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[11], line 1
----> 1 from nuplan.planning.script.run_training import main as main_train
      3 # Run the training loop, optionally inspect training artifacts through tensorboard (above cell)
      4 main_train(cfg)

File E:\nuplan\nuplan\planning\script\run_training.py:15
     13 from nuplan.planning.script.profiler_context_manager import ProfilerContextManager
     14 from nuplan.planning.script.utils import set_default_path
---> 15 from nuplan.planning.training.experiments.caching import cache_data
     16 from nuplan.planning.training.experiments.training import TrainingEngine, build_training_engine
     18 logging.getLogger('numba').setLevel(logging.WARNING)

File E:\nuplan\nuplan\planning\training\experiments\caching.py:17
     15 from nuplan.database.common.blob_store.s3_store import S3Store
     16 from nuplan.planning.scenario_builder.abstract_scenario import AbstractScenario
---> 17 from nuplan.planning.scenario_builder.nuplan_db.nuplan_scenario_filter_utils import (
     18     discover_log_dbs,
     19     get_db_filenames_from_load_path,
     20 )
     21 from nuplan.planning.script.builders.model_builder import build_torch_module_wrapper
     22 from nuplan.planning.script.builders.scenario_building_builder import build_scenario_builder

File E:\nuplan\nuplan\planning\scenario_builder\nuplan_db\nuplan_scenario_filter_utils.py:18
     16 from nuplan.common.utils.s3_utils import check_s3_path_exists, expand_s3_dir
     17 from nuplan.database.nuplan_db.nuplan_scenario_queries import get_scenarios_from_db
---> 18 from nuplan.planning.scenario_builder.nuplan_db.nuplan_scenario import NuPlanScenario
     19 from nuplan.planning.scenario_builder.nuplan_db.nuplan_scenario_utils import (
     20     DEFAULT_SCENARIO_NAME,
     21     ScenarioMapping,
     22     download_file_if_necessary,
     23 )
     24 from nuplan.planning.utils.multithreading.worker_utils import WorkerPool, worker_map

File E:\nuplan\nuplan\planning\scenario_builder\nuplan_db\nuplan_scenario.py:12
     10 from nuplan.common.maps.abstract_map import AbstractMap
     11 from nuplan.common.maps.maps_datatypes import PointCloud, TrafficLightStatusData, Transform
---> 12 from nuplan.common.maps.nuplan_map.map_factory import get_maps_api
     13 from nuplan.common.maps.nuplan_map.utils import get_roadblock_ids_from_trajectory
     14 from nuplan.database.common.blob_store.blob_store import BlobStore

File E:\nuplan\nuplan\common\maps\nuplan_map\map_factory.py:8
      6 from nuplan.common.maps.abstract_map_factory import AbstractMapFactory
      7 from nuplan.common.maps.nuplan_map.nuplan_map import NuPlanMap
----> 8 from nuplan.database.maps_db.gpkg_mapsdb import GPKGMapsDB
      9 from nuplan.database.maps_db.imapsdb import IMapsDB
     12 class NuPlanMapFactory(AbstractMapFactory):

File E:\nuplan\nuplan\database\maps_db\gpkg_mapsdb.py:1
----> 1 import fcntl
      2 import glob
      3 import json

ModuleNotFoundError: No module named 'fcntl'

```

Please someone look into where I have made mistake or what I need to change. Thank you

**Comment by ankithadam** [comment]
I even unistalled everything and tried running and uploading dataset in C drive but I am still getting the same issue: ModuleNotFoundError: No module named 'fcntl'

**Comment by DinnuGithub** [comment]
I am trying to create a flask application. Here is the code below.
Lokakshema.py:

from flask import Flask, request, jsonify
from flask_sqlalchemy import SQLAlchemy


app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///patients.db'
db = SQLAlchemy(app)

class Patient(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    age = db.Column(db.Integer)
    gender = db.Column(db.String(10))
    address = db.Column(db.String(100))
    contact_number = db.Column(db.String(20))

class HealthCheck(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    patient_id = db.Column(db.Integer, db.ForeignKey('patient.id'))
    symptoms = db.Column(db.String(200))
    temperature = db.Column(db.Float)
    blood_pressure = db.Column(db.String(20))
    diagnosis = db.Column(db.String(200))

@app.route('/patients', methods=['GET', 'POST'])
def patients():
    if request.method == 'POST':
        name = request.json['name']
        age = request.json['age']
        gender = request.json['gender']
        address = request.json['address']
        contact_number = request.json['contact_number']
        patient = Patient(name=name, age=age, gender=gender, address=address, contact_number=contact_number)
        db.session.add(patient)
        db.session.commit()
        return jsonify({'message': 'Patient created successfully!'})
    else:
        patients = Patient.query.all()
        output = []
        for patient in patients:
            patient_data = {'id': patient.id, 'name': patient.name, 'age': patient.age, 'gender': patient.gender, 'address': patient.address, 'contact_number': patient.contact_number}
            output.append(patient_data)
        return jsonify({'patients': output})

@app.route('/health-check', methods=['POST'])
def health_check():
    patient_id = request.json['patient_id']
    symptoms = request.json['symptoms']
    temperature = request.json['temperature']
    blood_pressure = request.json['blood_pressure']
    diagnosis = request.json['diagnosis']
    health_check = HealthCheck(patient_id=patient_id, symptoms=symptoms, temperature=temperature, blood_pressure=blood_pressure, diagnosis=diagnosis)
    db.session.add(health_check)
    db.session.commit()
    return jsonify({'message': 'Health check-up submitted successfully!'})

if __name__ == '__main__':
    app.run()
    
    
    
    And when I tried to run this through gunicorn I received the below error. Can any one help?
    
    
(venv) C:\Users\dinesh.n>gunicorn Lokakshema:app
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\dinesh.n\PycharmProjects\pythonProject1\venv\Scripts\gunicorn.exe\__main__.py", line 4, in <module>
  File "C:\Users\dinesh.n\PycharmProjects\pythonProject1\venv\Lib\site-packages\gunicorn\app\wsgiapp.py", line 9, in <module>
    from gunicorn.app.base import Application
  File "C:\Users\dinesh.n\PycharmProjects\pythonProject1\venv\Lib\site-packages\gunicorn\app\base.py", line 11, in <module>
    from gunicorn import util
  File "C:\Users\dinesh.n\PycharmProjects\pythonProject1\venv\Lib\site-packages\gunicorn\util.py", line 8, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

**Comment by ankithadam** [comment]
> Seems like fcntl is not available on Windows. I ran into the same problem when using the visualization tutorial file. Commenting that import line seems to have resolved it for now since I don't need this package yet.

Exactly true, this code isn't for windows. I should have known when I didn't see any installation process for windows but it was available only for MacOS and linux. I will close this issue as fcntl error did not occur in ubuntu
