### ISSUE TITLE
Question about submission‘s evaluation execution time

### ISSUE THREAD

**Issue by Shi-Qi-Li** [motional/nuplan-devkit#247]
Hi team,
How long does it take to get results after docker submitting?

**Comment by patk-motional** [comment]
Hi @Shi-Qi-Li,

We are manually triggering submission at the moment. Once triggered it should take around 2-3 hours for the results to be returned. In the future, this process will be automatic.

**Comment by Shi-Qi-Li** [comment]
> Hi @Shi-Qi-Li,
> 
> We are manually triggering submission at the moment. Once triggered it should take around 2-3 hours for the results to be returned. In the future, this process will be automatic.

So the submission in `Submitted` status but does't return results because it has not been triggered?

**Comment by patk-motional** [comment]
Correct, this will become automatic soon

**Comment by Shi-Qi-Li** [comment]
> Hi @Shi-Qi-Li,
> 
> We are manually triggering submission at the moment. Once triggered it should take around 2-3 hours for the results to be returned. In the future, this process will be automatic.

Hi @patk-motional ,
I have another question, I want to know if the result return is automatic? Because my submission has been running for a week now but no results have been returned yet.

**Comment by patk-motional** [comment]
Hi @Shi-Qi-Li,

Did your submission's status say submitted or running? If submitted then we have not triggered it yet.

**Comment by Shi-Qi-Li** [comment]
> Hi @Shi-Qi-Li,
> 
> Did your submission's status say submitted or running? If submitted then we have not triggered it yet.

The status of my submission is running.

**Comment by gianmarco-motional** [comment]
@Shi-Qi-Li  I believe you submitted the simulation container instead of your submission container. This caused a bad start on the execution and that's why it was marked running, but it actually failed almost immediately.

**Comment by Shi-Qi-Li** [comment]
> @Shi-Qi-Li I believe you submitted the simulation container instead of your submission container. This caused a bad start on the execution and that's why it was marked running, but it actually failed almost immediately.

Thanks for your reply! I resubmitted the submission container, could you please trigger it?
