### ISSUE TITLE
Problems loading gpkg using NuPlanMapWrapper

### ISSUE THREAD

**Issue by nelsondmmg** [motional/nuplan-devkit#248]
I'm having problems loading the map file (*.gpkg) during the initialization of an NuPlanMapWrapper object. The following error message is shown (after it tries to execute self._maps_db.get_raster_layer_names(map_name), line 32 at map_api.py):

`**rasterio.errors.RasterioIOError: '/home/ndemoura/Documents/datasets/nuScenes/dataset/maps/us-pa-pittsburgh-hazelwood/9.17.1937/map.gpkg' not recognized as a supported file format.**`

More specifically, the error happens when the function _get_map_dataset is executed, at the `return rasterio.open9path_on_disk)`

Did anyone observe this error? 
Btw, the tutorials ran without any errors, the maps were loaded correctly.
Thanks,

**Comment by patk-motional** [comment]
Hi @nelsondmmg,

Can you share how to recreate the issue?
