### ISSUE TITLE
how could I download the dataset with a command line in Linux?  How could I get specific url for downloading?

### ISSUE THREAD

**Issue by yaqlee** [motional/nuplan-devkit#249]
Could I use wget or python scripts to download all the dataset to specific file folder?

**Comment by mh0797** [comment]
Hi @yaqlee,
Yes you can. But it’s a bit hacky as the actual download link is only generated once you click on the button. To get the download link for a Linux machine, I used the Edge Browser on a windows machine and did the following. Go to the website, log in and find the download section below. Then click on the download button for the file you want to get. You can immediately stop the download and right click on the progress that’s being displayed. There you find the option to copy the download link.

Then you can do `wget -O Filename.zip „download link“`

Important Note:
Use the -O flag and quotations around the actual link, as the link contains special characters and you probably don’t want this long name as a filename.
Mind the capitalization, if the -O flag!

while this solution is more of a workaround, i hope it helps!
