### ISSUE TITLE
May I ask a simple question, how is the route labeled?

### ISSUE THREAD

**Issue by CrisCloseTheDoor** [motional/nuplan-devkit#255]
Hi developers:
I noticed some of the lane is labeled as "state on route". The lanes labeled can form an area surrounding ego and stretched forward for a distance. Could you please tell me how a lane is judged as "route"? Is there an algorithm to label, or just by hand?

**Comment by patk-motional** [comment]
Hi @CrisCloseTheDoor,

We infer the route from the expert-driven trajectory. The route is made up of a collection of RoadBlocks. Each Roadblock is a collection of lanes. The algorithm, we used tracks what road block the ego drove over. For every sample, the route is the collection of Roadblocks that the ego drove into the future for some time and distance. @gianmarco-motional can elaborate on it further.

**Comment by gianmarco-motional** [comment]
Yes fundamentally the route is what the expert drove (extracted algorithmically), retaining the previous roadblock and between 200m to 400m in the future

**Comment by CrisCloseTheDoor** [comment]
Thanks @patk-motional @gianmarco-motional
