### ISSUE TITLE
Bug in extract LidarPc token: simulation and training errors

### ISSUE THREAD

**Issue by HWOLFeng** [motional/nuplan-devkit#26]
This query seems wrong.
https://github.com/motional/nuplan-devkit/blob/40a7fb3d100ed8e4e4808cf8712647ae2d49e70f/nuplan/planning/scenario_builder/nuplan_db/nuplan_scenario_utils.py#L205-L211

Error Result:
![ego_at_pudo](https://user-images.githubusercontent.com/21254842/150468591-e32b9871-4ce3-40b8-acba-5bcadddc1e6c.png)

Fix Solution:
```
lidarpcs = db.session.query(LidarPc). \
    filter(LidarPc.timestamp > start_timestamp,
           LidarPc.timestamp < end_timestamp). \
    join(Lidar). \
    filter(Lidar.log_token == anchor_lidarpc.lidar.log_token). \
    order_by(LidarPc.timestamp.asc()). \
    all()
```
Result:
![Screenshot from 2022-01-21 12-54-30](https://user-images.githubusercontent.com/21254842/150468609-ae1b750c-7fcd-487c-b272-638665388f8d.png)

**Comment by kokseang-motional** [comment]
Hi @HWOLFeng 
Thanks for reporting this and provide the fix to us, would u mind sharing which scenario caused this as well?
Thanks 
FYI 
@dimitris-motional

**Comment by HWOLFeng** [comment]
> 

Dataset: 
nuplan_v0.2.db
Simulation setting sample: 
```python
log_names = ['2021.05.13.17.53.42_35_1620928475535573.2_1620934263535070.5']
scenario_types = ['ego_at_pudo']
# experiment_name is custom
default_overrides = ['scenario_builder=nuplan', 'experiment_name=simulation_test', 'log_config=false',
                     'planner=simple_planner', 'scenario_builder.nuplan.scenario_filter.subsample_ratio=0.01',
                     'exit_on_failure=true',
                     f'scenario_builder.nuplan.scenario_filter.log_names={log_names}',
                     f'scenario_builder.nuplan.scenario_filter.scenario_types={scenario_types}',
                     'scenario_builder.nuplan.scenario_filter.limit_scenarios_per_type=1',
                     'observation=box_observation', 'ego_controller=log_play_back_controller']
```
then debug simulation mode show: 
`anchor_lidarpc.lidar.log_token` equal `'e6b31c23506651aba71362ac96940b68'`
`set(lidarpc_token)` will be `{'e6b31c23506651aba71362ac96940b68', '9ae091ad536458839f7407c3392c7fd6'}`
But `lidarpc_token` must equal token `e6b31c23506651aba71362ac96940b68`


More Detail:
Not only `scenario_types = ['ego_at_pudo']` will have this bug. It also happens in other scenario.

**Comment by kokseang-motional** [comment]
Thanks for reporting this to us, we will fix this in the next version.
