### ISSUE TITLE
Concerns of the NuPlan Dataset

### ISSUE THREAD

**Issue by Curtainzsl** [motional/nuplan-devkit#261]
We want to know whether the nuplan dataset contains point cloud information. Thank you so much and please let us know if there is any concerns.

**Comment by bulbcult** [comment]
YES

**Comment by Curtainzsl** [comment]
> YES
Could you can help me locate the point could data ? Thank  you very much！

**Comment by bulbcult** [comment]
It's in the .db file, you need a "DB browser for SQLite" to open it, cheers

**Comment by Curtainzsl** [comment]
> 它在.db文件中，你需要一个“SQLite数据库浏览器”才能打开它，干杯

Thank you very much. I also have a question about whether we can use the point cloud as input to the planner?Thank you so much!

**Comment by bulbcult** [comment]
As indicated in "Database Schema" of tutorial/nuplan_advanced_model_training.ipynb:
"While there is a lot of information present in the diagram, the most important table is the `lidar_pc` table. Rows in this table are used to define a scenario."
I suppose point cloud is used to define a scenario, maybe you render it as input. Hope this helps u a bit :)

**Comment by gianmarco-motional** [comment]
@Curtainzsl Raw lidar data is not released yet, but will be very soon. Stay tuned for release `1.2.0`. For being able to run the simulation using it, will probably take a bit longer.
