### ISSUE TITLE
questions about the meaning of the vector inputs

### ISSUE THREAD

**Issue by nortonlrc** [motional/nuplan-devkit#262]
We have run the mlp baseline given by motional and try to figure out how raw information are extracted as vector features. We output the input tensors in the forward process, and found that the size of agent.ego is [8*5*3], agent.agents is [8*5*25*8]. vector_map_coor is[8*1520*2*2]. Our question is that could you tell us what each dimension of these vectors mean? Currently we only infer that the first dimension denotes history frames. Thank you for your answer!

**Comment by patk-motional** [comment]
Hi @nortonlrc,

You might be looking for the [vector_map](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/training/preprocessing/features/vector_map.py#L28) feature and [agents](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/training/preprocessing/features/agents.py#L18) feature. Please give it a look. You may follow up here for further questions.
