### ISSUE TITLE
The Visualization of Goal in Nuboard Scenario

### ISSUE THREAD

**Issue by yaqlee** [motional/nuplan-devkit#264]
### Description
 It would be convienient to have a feature that the goal of mission was visible in nuboard scenario tag. 
### Related Problem
N

### Describe alternatives you've considered
It is also great to give a tutorial on how to make the goal visible in nuboard.

### Additional context
N

**Comment by patk-motional** [comment]
Hi @yaqlee,

This feature already exists. 
![image](https://user-images.githubusercontent.com/95635553/232403966-7a8c45a4-55f1-4949-9807-4a1e4b82cdc3.png)
The mission goal is often much further away than the initial zoom distance. To ensure that the mission goal appears, make sure you have the goal checkbox ticked.
