### ISSUE TITLE
where is maps_tutorials.ipynb?

### ISSUE THREAD

**Issue by Christopher6488** [motional/nuplan-devkit#265]
I want to know to details of map, including the way of accessing, data structure, etc. The comment of NuPlanMapWrapper is "Before using this class please use the provided tutorial `maps_tutorials.ipynb`." . I want to know where is maps_tutorials.ipynb? Thanks a lot!

**Comment by patk-motional** [comment]
Hi @Christopher6488, 

We have deprecated the maps tutorial. The NuPlanMapWrapper is a legacy interface. Instead, you should be using the [NuPlanMap](https://github.com/motional/nuplan-devkit/blob/master/nuplan/common/maps/nuplan_map/nuplan_map.py). This is the interface that we are using throughout the codebase. Currently, we do not have the bandwidth to create a new tutorial for the map, unfortunately. I'm happy to answer your questions here if you have any.
