### ISSUE TITLE
Question about gpu used in competition

### ISSUE THREAD

**Issue by Shi-Qi-Li** [motional/nuplan-devkit#266]
Hi team,
I want to know the model of graphics card used in the competition. 
Thanks.

**Comment by patk-motional** [comment]
@gianmarco-motional can you help answer this one?

**Comment by Shi-Qi-Li** [comment]
> Hi @Shi-Qi-Li, is this information enough for you? https://nuplan-devkit.readthedocs.io/en/latest/competition.html#evaluation-server

Thanks for your reply! Perhaps I did not express my question clearly, I know there is 1 GPU for simulation but I hope to get the specific device model, like RTX x0x0.
