### ISSUE TITLE
Are reactive agents working reliably in closed-loop simulations?

### ISSUE THREAD

**Issue by d451gon** [motional/nuplan-devkit#268]
I've just started running some simulations with the SimplePlanner to test the different settings, and I'm getting very odd behaviors when using reactive agents in closed-loop simulations (see gifs below):

![near_multiple_vehicles_SimplePlanner_6cc3a86c636d566d](https://user-images.githubusercontent.com/7421687/232523892-c85d8ab6-4881-4e1a-ac61-cb95d400e7cf.gif)
![stationary_in_traffic_SimplePlanner_68c52fcabbf35ff4](https://user-images.githubusercontent.com/7421687/232523952-8ee04e32-8b81-45c5-aa39-509d911ffad1.gif)

Using the latest release (1.1).
Code to generate the first gif:

```
python run_simulations.py +simulation=closed_loop_reactive_agents scenario_filter.limit_total_scenarios=10 scenario_filter.timestamp_threshold_s=70
```

The first gif corresponds to the only scenario of type "near_multiple_vehicles" that results from running the code above (note that this is from the log 2021.07.16.20.45.29_veh-35_01095_01486, in the mini dataset, as per the default config).

The second gif is from a different log, just to double check.

Additionally, the number of vehicles surrounding the ego-vehicle in these simulations appears to be suspiciously low, although this might be a coincidence.

Thanks in advance for any insights!

**Comment by patk-motional** [comment]
Hi @d451gon,

I tried it myself but I don't seem to be able to recreate the issue. I was able to generate the gif below.

![closed-loop-reactive-agents](https://user-images.githubusercontent.com/95635553/232704257-645c926a-4c4b-4cc7-9f6d-d444326bda6d.gif)

**Comment by tenetwang** [comment]
Hi @patk-motional:

How to generate such viz result and gif? After running simulation through run_simulation.py with SimplePlanner under open loop just as the tutorial's guidance, results including .nuboard file and summary pdf are generated. However, when using run_nuboard.py to visualize, I could only get valid content on the 'Overview'  page, and the 'Histogram' and 'Scenarios' page is emtpy.

Looking forward to your guidance !

**Comment by d451gon** [comment]
Same as in #254 downgrading numpy from 1.24.2 to 1.23.4 solved the issue.

Thanks @patk-motional !
