### ISSUE TITLE
how to run the script without multi-process?

### ISSUE THREAD

**Issue by HeYDwane3** [motional/nuplan-devkit#27]
Hi nuPlan team,

It seems that the ray will initiate multi-process even only ONE gpu is allowed. With multi-process initiated, it would very difficult to debug.

I do not have much experience about distributed computing, could you guys please tell me how to modify the cfg to run the code with single process? Or is there any turorial to debug with multi-process code?

Thanks!

**Comment by HWOLFeng** [comment]
Example debug simulation  :
https://github.com/motional/nuplan-devkit/blob/3c4f5b8dcd517b27cfd258915ca5fe5c54e3cb0c/nuplan/planning/simulation/runner.py#L69-L70
Rewirte to: 
```python
# results: List[SimulationReport] = worker.map(Task(fn=run_simulation, num_gpus=num_gpus, num_cpus=num_cpus),
#                                             simulations, exit_on_failure)

results = [run_simulation(simulations[0], exit_on_failure)]
```

**Comment by dimitris-motional** [comment]
Hi @HeYDwane3, by default `worker=ray_distributed` is used in the config, you can pass `worker=sequential` instead for debugging.
