### ISSUE TITLE
omegaconf.errors.InterpolationToMissingValueError: MissingMandatoryValue while resolving interpolation: Missing mandatory value: job_name     full_key: hydra.run.dir     object_type=dict

### ISSUE THREAD

**Issue by indranilmaji** [motional/nuplan-devkit#270]
Is there a possible way to mitigate this error. I am very new to hydra and I cannot understand how to resolve this. This happens when I am trying to execute run_training.py to understand the pipeline of the codebase better.

**Comment by patk-motional** [comment]
Hi @indranilmaji,

Can you share the command you were trying to run?
