### ISSUE TITLE
Ego Controller Selection

### ISSUE THREAD

**Issue by FuxeyHuang** [motional/nuplan-devkit#278]
Hi there,

I wonder if we could choose ego controller during the final challenge phrase. We noticed that TWO_STAGE_CONTROLLER is used in the default settings of closed loop tasks in config while PERFECT_TRACKING is used in the planner tutorial. Can I assume that both of them is applicable? 

Moreover is it possible to write our own controller?

thx!

**Comment by patk-motional** [comment]
Hi @FuxeyHuang,

If you are doing your own development then the answer to both of your questions is yes. Any controller should be useable for the simulation.

For the competition, on the other hand, you CANNOT choose your controller or develop your own. This is to make the competition fair and comparable for all participants.
