### ISSUE TITLE
Request for assistance in setting up a simulation

### ISSUE THREAD

**Issue by iszhaotong** [motional/nuplan-devkit#279]
Dear nuPlan committee,
I am writing to request your assistance in setting up a simulation as described in the official documentation. Specifically, I am looking for the parameters and their corresponding files needed to set the simulation with the following specifications:
- Rollout horizon = 15s
- ml-planner (horizon length = 8s)
Could you please provide me with these files or let me know where I can find them? Additionally, any guidance or instructions on how to configure the simulation would be greatly appreciated.

**Comment by patk-motional** [comment]
Hi @iszhaotong,

- Rollout horizon: you can modify the length [here](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/script/config/common/scenario_builder/scenario_mapping/nuplan_scenario_mapping.yaml) 
- ml-planner: depends on which planner you are using. For vector model, you can modify it [here](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/script/config/common/model/vector_model.yaml#L29) . Each model has its own configuration.

Hope that helps!
