### ISSUE TITLE
Is there any plan on when to release the improved ml_planner？

### ISSUE THREAD

**Issue by HeYDwane3** [motional/nuplan-devkit#28]
Hi @StefanoS90, thank you for studying our devkit!

You are right, as of now, the initial versions are not using mission goal. The released planners are just simplified versions that can be trained, but they do not serve as baselines yet. In our next version, we will include this feature as well and improve the model performance.

_Originally posted by @juraj-motional in https://github.com/motional/nuplan-devkit/issues/19#issuecomment-1012382087_

**Comment by holger-motional** [comment]
Hi @HeYDwane3. We will release the 1.0 version of nuPlan in mid-April and it will also include major updates to the ML planner.
