### ISSUE TITLE
Errors in docker-compose up --build

### ISSUE THREAD

**Issue by Ydrg9989** [motional/nuplan-devkit#280]
Dear developers:
Some erros occured when I tried to submit. I have no idea to solve this problem.
This is detials of the probelm:

(nuplan) yang@crasher:~/nuplan-devkit$ docker-compose up --build
WARN[0000] The "NUPLAN_PLANNER" variable is not set. Defaulting to a blank string.
WARN[0000] The "NUPLAN_CHALLENGE" variable is not set. Defaulting to a blank string.
[+] Building 909.6s (31/32)                                                    
[+] Building 909.8s (31/32)                                                    
[+] Building 939.2s (32/32) FINISHED                                                                                                                                              
 => [nuplan/test-submission internal] load build definition from Dockerfile.submission                                                                                        0.2s
 => => transferring dockerfile: 2.21kB                                                                                                                                        0.0s
 => [nuplan/nuplan internal] load build definition from Dockerfile                                                                                                            0.2s
 => => transferring dockerfile: 2.42kB                                                                                                                                        0.0s
 => [nuplan/test-submission internal] load .dockerignore                                                                                                                      0.2s
 => => transferring context: 148B                                                                                                                                             0.0s
 => [nuplan/nuplan internal] load .dockerignore                                                                                                                               0.2s
 => => transferring context: 148B                                                                                                                                             0.0s
 => [nuplan/nuplan internal] load metadata for [docker.io/library/ubuntu:20.04](http://docker.io/library/ubuntu:20.04)                                                                                                 0.9s
 => CACHED [nuplan/test-submission  1/13] FROM [docker.io/library/ubuntu:20.04@sha256:db8bf6f4fb351aa7a26e27ba2686cf35a6a409f65603e59d4c203e58387dc6b3](http://docker.io/library/ubuntu:20.04@sha256:db8bf6f4fb351aa7a26e27ba2686cf35a6a409f65603e59d4c203e58387dc6b3)                         0.0s
 => [nuplan/nuplan internal] load build context                                                                                                                               0.5s
 => => transferring context: 7.73MB                                                                                                                                           0.3s
 => [nuplan/test-submission internal] load build context                                                                                                                      0.5s
 => => transferring context: 7.73MB                                                                                                                                           0.4s
 => [nuplan/nuplan  2/13] RUN apt-get update     && apt-get install -y curl gnupg2 software-properties-common default-jdk                                                   119.9s
 => [nuplan/test-submission  3/13] RUN curl -fsSL https://bazel.build/bazel-release.pub.gpg | apt-key add -     && curl -fsSL https://nvidia.github.io/nvidia-docker/gpgkey  35.0s
 => [nuplan/nuplan  3/13] RUN curl -fsSL https://bazel.build/bazel-release.pub.gpg | apt-key add -     && curl -fsSL https://nvidia.github.io/nvidia-docker/gpgkey | apt-ke  47.3s
 => [nuplan/test-submission  4/13] RUN curl -fsSLo Miniconda3-latest-Linux-x86_64.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh &&     bash Mini  10.8s
 => [nuplan/test-submission  5/13] WORKDIR /nuplan_devkit                                                                                                                     0.1s
 => [nuplan/test-submission  6/13] COPY requirements.txt requirements_torch.txt requirements_submission.txt environment_submission.yml /nuplan_devkit/                        0.1s
 => [nuplan/test-submission  7/13] RUN conda env create -f /nuplan_devkit/environment_submission.yml                                                                        679.9s
 => [nuplan/nuplan  4/13] RUN curl -fsSLo Miniconda3-latest-Linux-x86_64.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh &&     bash Miniconda3-la  10.8s
 => [nuplan/nuplan  5/13] WORKDIR /nuplan_devkit                                                                                                                              0.0s
 => [nuplan/nuplan  6/13] COPY requirements.txt requirements_torch.txt environment.yml /nuplan_devkit/                                                                        0.1s
 => [nuplan/nuplan  7/13] RUN PIP_EXISTS_ACTION=w conda env create -f /nuplan_devkit/environment.yml                                                                        667.5s
 => [nuplan/nuplan  8/13] RUN mkdir -p /nuplan_devkit/nuplan                                                                                                                  0.6s
 => [nuplan/test-submission  8/13] RUN mkdir -p /nuplan_devkit/nuplan                                                                                                         0.6s
 => [nuplan/nuplan  9/13] COPY setup.py /nuplan_devkit                                                                                                                        0.2s
 => [nuplan/test-submission  9/13] COPY setup.py /nuplan_devkit                                                                                                               0.2s
 => [nuplan/nuplan 10/13] COPY nuplan /nuplan_devkit/nuplan                                                                                                                   0.6s
 => [nuplan/test-submission 10/13] COPY nuplan /nuplan_devkit/nuplan                                                                                                          0.4s
 => [nuplan/test-submission 11/13] RUN bash -c "pip install -e ."                                                                                                             3.7s
 => [nuplan/nuplan 11/13] RUN bash -c "pip install -e ."                                                                                                                      3.5s
 => [nuplan/nuplan 12/13] RUN bash -c 'mkdir -p {$NUPLAN_MAPS_ROOT,$NUPLAN_DATA_ROOT,$NUPLAN_EXP_ROOT}'                                                                       1.3s
 => [nuplan/test-submission 12/13] RUN bash -c 'mkdir -p {$NUPLAN_MAPS_ROOT,$NUPLAN_DATA_ROOT,$NUPLAN_EXP_ROOT}'                                                              1.4s
 => [nuplan/nuplan 13/13] RUN bash -c 'mkdir -p $NUPLAN_DB_FILES'                                                                                                             1.3s
 => [nuplan/test-submission 13/13] RUN apt-get update     && apt-get install -y     awscli     && rm -rf /var/lib/apt/lists/*                                                52.0s
 => [nuplan/test-submission] exporting to image                                                                                                                              70.4s
 => => exporting layers                                                                                                                                                      33.8s
 => => writing image sha256:537a27cdb1ad36f5ec6536de085122dffb4f1a67dfcc5a18db2cc8d3789b868f                                                                                  0.0s
 => => naming to [docker.io/nuplan/nuplan](http://docker.io/nuplan/nuplan)                                                                                                                                      0.0s
 => => writing image sha256:cae302337b8a3c2964d870ae32d6e6364e6d295726eb9ed6cd6d22110663d11a                                                                                  0.0s
 => => naming to [docker.io/nuplan/test-submission](http://docker.io/nuplan/test-submission)                                                                                                                             0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 2/1
 ⠿ Container nuplan-devkit-submission-1  Created                                                                                                                              0.1s
 ⠿ Container nuplan-devkit-simulation-1  Created                                                                                                                              0.1s
Attaching to nuplan-devkit-simulation-1, nuplan-devkit-submission-1
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown

Thank you in advance

**Comment by patk-motional** [comment]
Tagging @gianmarco-motional

**Comment by Ydrg9989** [comment]
@gianmarco-motional Hi, could you give me some suggestions?

**Comment by gianmarco-motional** [comment]
Hey @Ydrg9989,

The issue here can be very broad and is difficult for me to find a cause without trying on the system you are using. It seems related to nvidia drivers. I would suggest to proceed by steps (run nvidia-smi, run the same withing a container, etc.), and of course look for similar problems on Google.

Unfortunately is not a problem on our side and I can't help much more thant that.
