### ISSUE TITLE
How to submit results to EvalAI by a self-developed model

### ISSUE THREAD

**Issue by xzag008** [motional/nuplan-devkit#282]
Hi,

I have extracted and preprocessed data from nuplan-v1.1_mini and trained my model to output agents' (x, y, heading).
Now, I want to know how to submit results to EvalAI, or say
1) How to get data in the test phase (without ground truth)?
2) How to transform the model's output to the submit format?

**Comment by xzag008** [comment]
The training and evaluation of my model don't call any codes in nuplan-devkit.

**Comment by michael-motional** [comment]
Hey @xzag008, you have to integrate with the devkit to make a submission -- you submit a image, and we run your code to evaluate. [Here](https://nuplan-devkit.readthedocs.io/en/latest/competition.html#making-a-submission) are the submission instructions, let me know if you have any problems.
