### ISSUE TITLE
Can we use rule based planner to take part in the competition?

### ISSUE THREAD

**Issue by piqiuni** [motional/nuplan-devkit#288]
Can we use rule based planner to take part in the competition?
And our planner runs in ROS, can it be configured and committed in Docker？

Thanks!

**Comment by patk-motional** [comment]
Hi @piqiuni,

Yes, you may. As long as your planner adheres to our [abstract_planner](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/simulation/planner/abstract_planner.py) interface you should be able to participate.

Check this page to get started https://nuplan-devkit.readthedocs.io/en/latest/competition.html#how-to-enter
