### ISSUE TITLE
How can I get "mission goal" during simulation?

### ISSUE THREAD

**Issue by yaqlee** [motional/nuplan-devkit#289]
I wrote a function in agents_feature_builder to get mission goal during simulation, like this: 

> def get_features_from_simulation(self, current_input: PlannerInput, initialization: PlannerInitialization) 
> 
>     goal_ego_state = initialization.mission_goal
> 
>     goal_x = goal_ego_state.x

    
But I was encountered with log " 'NoneType' has no attribute 'x' ", so how can I get "mission goal" during simulation?

**Comment by patk-motional** [comment]
Hi @yaqlee,

Some scenarios have missing mission goals. You need to set `scenario_filter.remove_invalid_goals=true`. Hope that helps.
