### ISSUE TITLE
How to load an image

### ISSUE THREAD

**Issue by handsome-river** [motional/nuplan-devkit#29]
Hi!
I could initialize a NuPlanDB successfully,but i failed to load a image.
**os.environ['NUPLAN_DATA_ROOT']='/media/new_data4/nuplan/dataset'
db = NuPlanDB('nuplan_v0.1_mini', data_root=os.getenv('NUPLAN_DATA_ROOT'), map_version="nuplan-maps-v0.1")
img = db.image[0]
im = img.load_as(img_type='pil')**

And the error message was as follows:
Traceback (most recent call last):
  File "/media/new_data4/nuplan-devkit/nuplan/database/common/blob_store/local_store.py", line 40, in get
    with open(path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/media/new_data4/nuplan/dataset/blob://v1/2021.05.26.20.05.14_38_1622073985538950.8_1622074969538793.5/CAM_L0/jpeg/65101990:199356'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/new_data4/nuplan-devkit/test.py", line 30, in <module>
    im = img.load_as(img_type='pil')
  File "/media/new_data4/nuplan-devkit/nuplan/database/nuplan_db/models.py", line 923, in load_as
    pil_img = PIL.Image.open(self.load_bytes_jpg())
  File "/media/new_data4/nuplan-devkit/nuplan/database/nuplan_db/models.py", line 945, in load_bytes_jpg
    blob: BinaryIO = self.table.db.load_blob(self.filename)
  File "/media/new_data4/nuplan-devkit/nuplan/database/common/db.py", line 420, in load_blob
    return self._blob_store.get(path)   # type: ignore
  File "/media/new_data4/nuplan-devkit/nuplan/database/common/blob_store/local_store.py", line 43, in get
    raise BlobStoreKeyNotFound(e)
nuplan.database.common.blob_store.blob_store.BlobStoreKeyNotFound: [Errno 2] No such file or directory: '/media/new_data4/nuplan/dataset/blob://v1/2021.05.26.20.05.14_38_1622073985538950.8_1622074969538793.5/CAM_L0/jpeg/65101990:199356'

**Comment by holger-motional** [comment]
Thank you for your interest. It is correct that the teaser release does not include any sensor data (camera, lidar). We will make these available for a mini split in the full release (~mid April).

**Comment by handsome-river** [comment]
Thank you for your reminding.But I still want to get some useful information from the dataset,such as the historic or present ego and agent poses in the map.Can you provide some examples of obtaining these data informatioin?

**Comment by holger-motional** [comment]
Yes, all of the ego and agent poses on the map are available. I suggest you take a look at the tutorial: https://github.com/motional/nuplan-devkit/tree/master/tutorials (more to follow)

**Comment by handsome-river** [comment]
Thank you for your suggestion.What I want to do is make datasets like this
![individualImage](https://user-images.githubusercontent.com/100257978/156308639-4e2ac2dd-570c-417d-9209-454086c7433e.png)
Can you provide some demos about how to extract data from the database and turn them into images?
