### ISSUE TITLE
Some questions about docker submission of chanllenge.

### ISSUE THREAD

**Issue by Greatsjk** [motional/nuplan-devkit#295]
First, I don't know where to set the env variables NUPLAN_DATA_ROOT NUPLAN_MAPS_ROOT NUPLAN_EXP_ROOT. If I set them in [.env](https://github.com/motional/nuplan-devkit/blob/master/.env) It will influence the env variables in python files. So I only can set absolute path in docker-compose to simulate it. Does it influence the docker image running in your sever?
Second, I have encountered the following error in the simulation, but I don't know how to solve it. I don't know where and how to set this env variable and it is not defaulting to a blank string.
![sendpix0](https://github.com/motional/nuplan-devkit/assets/70321079/c6686eb6-9c06-4cd0-b964-063ef6c03615)

Third, I wonder how to make sure the submission is valid and how much data I need to simulate? If I simulate my planner successfully in docker only using one db file, can I make sure that my submission is valid?

**Comment by patk-motional** [comment]
Hi @Greatsjk,

Answering your questions in order:
1.  You can set this in your ~/.bashrc.
  a. No it will not influence running in our servers. We do not use your simulation image. We only take your submission image
2. You can try exporting SCENARIO_FILTER_ID in `nuplan-devkit/.env` like so `export SCENARIO_FILTER_ID=` 
3. If you can successfully run docker-compose then you should have a valid submission.

**Comment by Greatsjk** [comment]
Thanks for your replay. I have further questions about that. I have trained a ml_planner and use **urban_driver_open_loop_model**. ml_planner.yaml like this
![sendpix1](https://github.com/motional/nuplan-devkit/assets/70321079/21a689dc-f1b4-48a2-8cb1-c15accff352f)

And I copy the checkpoint to image in Dockerfile.submission use 
COPY epoch=0.ckpt /nuplan_devkit/

And set the env variable $NUPLAN_PLANNER
export NUPLAN_PLANNER = "ml_planner"

But I get this error info.
![sendpix2](https://github.com/motional/nuplan-devkit/assets/70321079/4ef68532-c82c-401e-b871-a7c9f1ab5027)
