### ISSUE TITLE
why define "valid" scenes as those that have at least 2 before and 2 after

### ISSUE THREAD

**Issue by Fan-Yixuan** [motional/nuplan-devkit#296]
Why is that?

https://github.com/motional/nuplan-devkit/blob/0dfdcd3f3dcd7e201200db31e70c0fd19ae4c269/nuplan/database/nuplan_db/nuplan_scenario_queries.py#L872-L881

Thanks for the help!

**Comment by patk-motional** [comment]
Hi @Fan-Yixuan,

This is because, for both training and simulation, we need to being to sample into the past and future. If we take a sample at the start or end of the log there would be insufficient data to do so.
