### ISSUE TITLE
Tutorial "nuplan_framework.ipynb" - TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by cgenctor** [motional/nuplan-devkit#30]
Hi Motional Team, 

thank you for publishing the dataset and for your effort in providing this benchmark. 
While running the tutorial nuplan_framework.ipynb I get these errors: 
```

File ~/nuplan-devkit/nuplan/database/utils/label/utils.py:35, in <module>
     30     local2id: Dict[str, int]
     33 def parse_labelmap_dataclass(
     34     labelmap: Dict[int, Label]
---> 35 ) -> Tuple[OrderedDict[int, Any], OrderedDict[int, Tuple[Any, ...]]]:
     36     """
     37     A labelmap provides a map from integer ids to text and color labels. After loading a label map from json, this
     38     will parse the labelmap into commonly utilized mappings and fix the formatting issues caused by json.
   (...)
     41         Label id to name and label id to color mappings tuple.
     42     """

TypeError: 'type' object is not subscriptable`


```
and 
```


ImportError: Encountered error: `'type' object is not subscriptable` when loading module 'nuplan.planning.scenario_builder.nuplan_db.nuplan_scenario_builder.NuPlanScenarioBuilder'

2022-07-06 12:56:30,501	WARNING worker.py:1257 -- (ip=134.91.77.153) The agent on node lab13 failed to be restarted 5 times. There are 3 possible problems if you see this error.
  1. The dashboard might not display correct information on this node.
  2. Metrics on this node won't be reported.
  3. runtime_env APIs won't work.
Check out the `dashboard_agent.log` to see the detailed failure messages.

```
Do you maybe know what this error is related to? Thanks

**Comment by patk-motional** [comment]
Hi @cgenctor,

We just updated the devkit can you try rebasing the newest master and give it a try?

**Comment by cgenctor** [comment]
Thank you for your reply @patk-motional , 

When I run the tutorial in a conda env with python 3.9 there is no issue but
there I do not have the GPU support.
In a pycharm virtual env with python 3.8, I have the GPU support, but I still face this issue. 
I have tried to run it with `Tuple[Dict[int, Any], Dict[int, Tuple[Any, ...]]]:`
instead of `Tuple[OrderedDict[int, Any], OrderedDict[int, Tuple[Any, ...]]]:`
and it works, however I don't know if I am supposed to run it this way

**Comment by patk-motional** [comment]
Unfortunately, we do not support python 3.8 anymore
