### ISSUE TITLE
How to run simulation with GPUs?

### ISSUE THREAD

**Issue by jchengai** [motional/nuplan-devkit#301]
I found that the default simulation setting uses all CPU cores.  How to properly set `number_of_gpus_allocated_per_simulation` , for example, for a single node machine with 4 GPUs?

**Comment by patk-motional** [comment]
Hi @jchengai,

We have not explored running with multiple GPUs on a single machine. I've mentioned in this [issue](https://github.com/motional/nuplan-devkit/issues/294#issue-1701377606) that setting `worker=sequential` is the easiest way to get GPU access.
