### ISSUE TITLE
What caused missing mission goal?

### ISSUE THREAD

**Issue by Fan-Yixuan** [motional/nuplan-devkit#303]
I understand that the missing mission goal scenes may be low-quality data, but I‘m curious about what causes this phenomenon. If my ml-based planner does not use mission goals (only roadblock ids to navigate), could those missing mission goal samples be low-quality samples for me?

**Comment by patk-motional** [comment]
Hi @Fan-Yixuan,

Since our logs were collected by a human driver there are no explicit goals and routes. Hence, we needed to infer a possible goal and route from the logs. We used some heuristics and graph search to generate the goals and routes. However, there are edge cases that caused some samples to have no goals.

Can you elaborate on your second point?

**Comment by Fan-Yixuan** [comment]
Thank you for your answer!
My second point: I found that scenes without mission goals do have 'roadblock_ids' (the route to their goal). **If a scene lacks a mission goal, can the roadblock_ids given in the dataset be trusted?** This determines whether my algorithm can use the data points. (My algorithm only uses roadblock_ids to navigate the ego vehicle)

**Comment by patk-motional** [comment]
Can you share some samples that are missing the mission goal but contains the roadblock_ids? If it contains the route then the mission_goal should be present as well.

**Comment by Fan-Yixuan** [comment]
Hi @patk-motional, this is 2021.08.18.18.32.06_veh-28_01425_01518 from boston

![example](https://github.com/motional/nuplan-devkit/assets/45420358/5aad2afd-7b63-42b0-8402-50019be68c23)

**Comment by Fan-Yixuan** [comment]
@patk-motional Hi, do you have any idea about this issue? Is there something wrong with my understanding of the dataset or what?

**Comment by patk-motional** [comment]
Hi @Fan-Yixuan,

I haven't had time to look into this yet, unfortunately. Will do as soon as I have the bandwidth to.
