### ISSUE TITLE
Please check the error report for all your 'Finished' submissions

### ISSUE THREAD

**Issue by patk-motional** [motional/nuplan-devkit#307]
Please check `Stderr file` even if your submission status is `Finished`. There could still be errors. 

We still compute the results on available successful scenarios completed. However, for the test phase, submissions with the most completed scenarios will take priority.

A successful submission should result in a `stderr` that looks similar to this:
```
Merged stderr:


remote_closed_loop_reactive_agents4.log

remote_closed_loop_reactive_agents2.log

remote_closed_loop_reactive_agents1.log

remote_open_loop_boxes5.log

remote_closed_loop_reactive_agents6.log

remote_closed_loop_nonreactive_agents3.log

remote_closed_loop_reactive_agents3.log

remote_open_loop_boxes7.log

remote_closed_loop_reactive_agents7.log

remote_closed_loop_nonreactive_agents4.log

remote_open_loop_boxes0.log

remote_closed_loop_reactive_agents5.log

remote_closed_loop_nonreactive_agents6.log

remote_closed_loop_reactive_agents0.log

remote_closed_loop_nonreactive_agents5.log

remote_open_loop_boxes2.log

remote_closed_loop_nonreactive_agents1.log

remote_closed_loop_nonreactive_agents0.log

remote_open_loop_boxes1.log

remote_closed_loop_nonreactive_agents7.log

remote_closed_loop_nonreactive_agents2.log

validation_challenge99.log

remote_open_loop_boxes6.log

remote_open_loop_boxes3.log

remote_open_loop_boxes4.log
```

**Comment by arunbalajeev** [comment]
Hey,
Where do we find the above logs?

**Comment by patk-motional** [comment]
You can find it here 
![image](https://github.com/motional/nuplan-devkit/assets/95635553/77dfed09-77fd-460a-a7f8-421abf1aab09)

Please join our slack https://github.com/motional/nuplan-devkit/issues/285. It seems that you have modified some paths to the map that may have caused your submission to fail
