### ISSUE TITLE
About how to use the data directly

### ISSUE THREAD

**Issue by HermanZYZ** [motional/nuplan-devkit#31]
Hi!
I am trying to use the data of nuplan directly, including the map data. But I do not know the meaning of fields in the dataset, such as 'left_has_reflectors' which is from SemanticMapLayer.LANE of the map. Is there any documents for helping use the dataset? Thanks a lot!

**Comment by patk-motional** [comment]
Hi, sorry for the delayed response!

We will be releasing documentation for this with the full release. 

In the meantime, you can access the map data through the NuPlanMap interface. Hope this helps

**Comment by HermanZYZ** [comment]
Thanks @patk-motional. It is effective. But there is still many datatypes without clear meaning. Looking forward to your full release.

By the way, I am trying to use the NuPlan DB directly  to reconstruct the motion scene, like a rosbag playing in ROS. Is there any interfaces to help me understand better how to use it.

Thanks a lot!

**Comment by HermanZYZ** [comment]
>

**Comment by HermanZYZ** [comment]
> Thanks @patk-motional. It is effective. But there is still many datatypes without clear meaning. Looking forward to your full release.
> 
> By the way, I am trying to use the NuPlan DB directly to reconstruct the motion scene, like a rosbag playing in ROS. Is there any interfaces to help me understand better how to use it.
> 
> Thanks a lot!

Or can I use Simulator separately. For example, giving a series of poses, Simulator returns a scenaro with objects, traffic light status, etc.

**Comment by patk-motional** [comment]
A NuplanScenario might be what you are looking for. It allows you to loop through the scenario returning Detections at every time step. As a side note, traffic lights are not available in the teaser yet. This will come with the full release :)

On the other hand, we have the simulation script that allows you to test your planner.

**Comment by HermanZYZ** [comment]
My planner is written with C++ that is a part of a driving system. Thus, it seems I can not use the simulation in devkit directly.

**Comment by patk-motional** [comment]
Can you write python bindings for it?

**Comment by HermanZYZ** [comment]
Good advice!
