### ISSUE TITLE
About the time out of  _compute_trajectory

### ISSUE THREAD

**Issue by yaqlee** [motional/nuplan-devkit#310]
When I ran docker compose locally, I logged the time out at 204th line in /nuplan_devkit/nuplan/planning/simulation/planner/remote_planner.py: function _compute_trajectory  like this:
![Bo9yIzlQrt](https://github.com/motional/nuplan-devkit/assets/49465987/26a5b163-2096-45c2-b8cc-d9583e7d64fc)

 the time out of the very first step is over 1s which caused failure in submission, and the time out of second step was reduced dramatically. Is there some difference between the first step and following steps?
 
![jeVN3vDuTF](https://github.com/motional/nuplan-devkit/assets/49465987/dcf5696d-6803-46d6-8022-9ae1a677b9cd)

if the ckpt file was over 100M, would the time out of the first step increase?

**Comment by piqiuni** [comment]
Maybe you use any init in the first frame?

**Comment by gianmarco-motional** [comment]
@piqiuni is this the default sample scenario used when running `docker compose`?

In the first iteration you have no cache, so it is expected that it is slightly more expensive than subsequent samples. However I timed our baselines, and there should not be such a big difference between samples. Are you sure you are not initializing planner related attributes when computing the trajectory?
