### ISSUE TITLE
Questions about submission

### ISSUE THREAD

**Issue by piqiuni** [motional/nuplan-devkit#312]
Our Planner use ROS to run several process, and it works well on our local platform, ROS use port localhost:11311 to communicate.
And we could run "docker-compose up" with simple_planner successfully.

But when running "docker-compose up" with our Planner, the GRPC connection between two containers would rase Error "Deadline Exceeded". We have checked that ROS uses port 11311 and GRPC uses 50051, which means they shouldn't run into conflict.

Can you give us any suggestion? 

Thanks!

**Comment by piqiuni** [comment]
Error Info:

> grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
nuplan-devkit-simulation-1  | 	status = StatusCode.DEADLINE_EXCEEDED
nuplan-devkit-simulation-1  | 	details = "Deadline Exceeded"
nuplan-devkit-simulation-1  | 	debug_error_string = "{"created":"@1684745213.775697606","description":"Error received from peer ipv6:[::1]:50051","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Deadline Exceeded","grpc_status":4}"

**Comment by patk-motional** [comment]
Tagging @gianmarco-motional to address this.

**Comment by patk-motional** [comment]
The error means that your planner is taking too long to complete one cycle. I don't think this is related to the issue you described above.

**Comment by piqiuni** [comment]
> The error means that your planner is taking too long to complete one cycle. I don't think this is related to the issue you described above.

Is there a time limit for the initialization of the program？
we called time.sleep(10) in the initialize(self, initialization: PlannerInitialization) to ensure that additional processes can be started

**Comment by patk-motional** [comment]
Yes, there is a time limit of 5 seconds in the initialization.
