### ISSUE TITLE
How to get the drivable area?

### ISSUE THREAD

**Issue by handsome-river** [motional/nuplan-devkit#32]
Hi! 
I wonder if there is a way to get a driveable area?
I use the function get_map_crop with the parameter 'map_layer_name'='drivable_area', but there seems to be no such file like 'drivable_area.npy'

**Comment by patk-motional** [comment]
Hi, sorry for the delayed response. 

Can you provide some more detail as to how you are calling the function?

Alternatively, you can get the drivable area through the NuPlanMap interface. There you can get the drivable area either as a raster or as a vector layer

**Comment by handsome-river** [comment]
Thanks for your advice!
I have solved this problem.
