### ISSUE TITLE
How to download metadata file of nuPlan v1.1 Dataset

### ISSUE THREAD

**Issue by nguyenlam185** [motional/nuplan-devkit#322]
Please anybody tell me how to download the metadata file.
I created an account and have all the zip files of the dataset v1.1 downloaded, except the metadata file.
When click on the Link (both US and Asia) there was just the loading icon appeared for a while, just like the other files, but then nothing happen
![image](https://github.com/motional/nuplan-devkit/assets/5319157/5049f44e-c574-4eae-af70-d24a1ce9cda4)

**Comment by patk-motional** [comment]
Hi @nguyenlam185,

We're about to update the website with the full sensor data release. Will take a look at this again if the issue persists.
