### ISSUE TITLE
sensor calibration data

### ISSUE THREAD

**Issue by qiang-sean-liu** [motional/nuplan-devkit#325]
Hi,

Thank you for releasing the sensor dataset. Where can I find the intrinsics of the cameras and the extrinsics between the sensors and the VCS?

Thanks!

Sean

**Comment by patk-motional** [comment]
Hi @qiang-sean-liu,

For a given DB file you can call this function [`get_cameras()`](https://github.com/motional/nuplan-devkit/blob/master/nuplan/database/nuplan_db/nuplan_scenario_queries.py#L1009). That should return a [`Camera`](https://github.com/motional/nuplan-devkit/blob/master/nuplan/database/nuplan_db/camera.py) class that exposes the [extrinsics](https://github.com/motional/nuplan-devkit/blob/master/nuplan/database/nuplan_db/camera.py) of the camera. Hope that helps.
