### ISSUE TITLE
CUDA: out of memory, with a batch_size 4 on 8 * V100 GPU cards.

### ISSUE THREAD

**Issue by shubaozhang** [motional/nuplan-devkit#33]
![image](https://user-images.githubusercontent.com/24953124/156976670-4cb2033d-da94-4ee5-bb06-3c1639e6a1f8.png)
import os
import hydra
import tempfile
from pathlib import Path
from nuplan.planning.script.run_training import main as main_train

# Location of path with all training configs
CONFIG_PATH = '../nuplan-devkit/nuplan/planning/script/config/training'
CONFIG_NAME = 'default_training'

# Create a temporary directory to store the cache and experiment artifacts
#SAVE_DIR = Path(tempfile.gettempdir()) / 'tutorial_nuplan_framework'  # optionally replace with persistent dir
SAVE_DIR = '/home/qcraft/nuplan/experiment/'  # optionally replace with persistent dir
EXPERIMENT = 'vector' # vector or raster or others
#LOG_DIR = str(SAVE_DIR / EXPERIMENT)
LOG_DIR = str(SAVE_DIR + '/' + EXPERIMENT)

# Initialize configuration management system
hydra.core.global_hydra.GlobalHydra.instance().clear()
hydra.initialize(config_path=CONFIG_PATH)

# Compose the configuration
cfg = hydra.compose(config_name=CONFIG_NAME, overrides=[
    f'group={str(SAVE_DIR)}',
    f'cache_dir={str(SAVE_DIR)}/cache',
    f'experiment_name={EXPERIMENT}',
    'log_config=true',
    'py_func=train',
    '+training=training_vector_model',  # vector model that consumes ego, agents and map vector layers and regresses the ego's trajectory
    'resume_training=true', # load the model from the last epoch and resume training
    'worker=single_machine_thread_pool', # ray_distributed, sequential, single_machine_thread_pool
    'scenario_builder=nuplan_mini',  # use nuplan or nuplan_mini database
    'scenario_builder.nuplan.scenario_filter.limit_scenarios_per_type=50000',  # Choose 500 scenarios to train with
    'scenario_builder.nuplan.scenario_filter.subsample_ratio=0.1',  # subsample scenarios from 20Hz to 0.2Hz
    'lightning.trainer.params.accelerator=ddp',  # ddp is not allowed in interactive environment, using ddp_spawn instead - this can bottleneck the data pipeline, it is recommended to run training outside the notebook
    'lightning.trainer.params.precision=16',
    'lightning.trainer.params.auto_scale_batch_size=false',
    'lightning.trainer.params.auto_lr_find=false',
    'lightning.trainer.params.gradient_clip_val=0.0',
    'lightning.trainer.params.gradient_clip_algorithm=norm',
    'lightning.trainer.params.accumulate_grad_batches=1', 
    'lightning.trainer.overfitting.enable=false',  # run an overfitting test instead of traning
    'lightning.optimization.optimizer.learning_rate=1e-4',
    'lightning.trainer.params.max_epochs=100',
    'lightning.trainer.params.gpus=8',
    'data_loader.params.batch_size=4',
    'data_loader.params.num_workers=32',
])

# Run the training loop, optionally inspect training artifacts through tensorboard (above cell)
main_train(cfg)
~

**Comment by holger-motional** [comment]
Hi. Thanks for creating the issue. Can you provide the exact command that you ran?

**Comment by holger-motional** [comment]
@shubaozhang
