### ISSUE TITLE
dataset confusion

### ISSUE THREAD

**Issue by changliucoding** [motional/nuplan-devkit#330]
Hi in nuplan devkit the dataset is structured as 
./nuplan/dataset/maps and nuplanv1.1.

But why in nuplan_sensor_data_tutorial is like 
NUPLAN_DATA_ROOT = "/data/sets/nuplan/"
NUPLAN_MAP_VERSION = "nuplan-maps-v1.0"
NUPLAN_MAPS_ROOT = "/data/sets/nuplan/maps"

where does /data/sets come from? And it is also different from the data structure above...

Also I wonder when you said ./nuplan/dataset, do you mean the nuplan folder inside the nuplan devkit folder, or we need to create a new nuplan folder outside the nuplan devkit...It confuses me

**Comment by CarlDegio** [comment]
same issue

**Comment by CarlDegio** [comment]
docker setting and local  setting should be apart?
