### ISSUE TITLE
sensor dataset downloading

### ISSUE THREAD

**Issue by qiang-sean-liu** [motional/nuplan-devkit#332]
Thank you for releasing the camera and lidar datasets. Could you please provide a script to download the data? Otherwise it is a challenge to download manually.
Thanks!!

**Comment by Syzygianinfern0** [comment]
https://github.com/Syzygianinfern0/NuPlan-Download-CLI

You can check this out!

**Comment by qiang-sean-liu** [comment]
thanks, it works!
