### ISSUE TITLE
Does sensor data support close-loop evaluation?

### ISSUE THREAD

**Issue by exiawsh** [motional/nuplan-devkit#335]
Hi, thanks for the great work! Does sensor data support close-loop evaluation? Or only aupport log-replay in open-loop training.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by patk-motional** [comment]
Unfortunately, it does not. Sensor data is only available in open-loop simulation
