### ISSUE TITLE
Visualize single observation

### ISSUE THREAD

**Issue by Syzygianinfern0** [motional/nuplan-devkit#338]
How can I visualize the `current_input: PlannerInput`? 

https://github.com/motional/nuplan-devkit/blob/cd3fd8d3d0c4d390fcb74d05fd56f92d9e0c366b/nuplan/planning/simulation/planner/simple_planner.py#L57

**Comment by Syzygianinfern0** [comment]
@christopher-motional could you please help me out if possible. Thanks!

**Comment by christopher-motional** [comment]
Hi @Syzygianinfern0, the devkit doesn't have anything out of the box for visualizing planner input, though perhaps you can [visualize the scenarios](https://github.com/motional/nuplan-devkit/blob/master/tutorials/utils/tutorial_utils.py#L216) the planner input is extracted from similar to what's being done in the [scenario visualization tutorial](https://github.com/motional/nuplan-devkit/blob/master/tutorials/nuplan_scenario_visualization.ipynb). You can see [here](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/simulation/simulation.py#L140) where the PlannerInput is constructed. The important part here is the history buffer which is an extraction of states from the scenario. Looking backward in frames for the scenario should give you a picture of what you're interested though -- or with a little work you could create a similar method to [serialize_scenario](https://github.com/motional/nuplan-devkit/blob/master/tutorials/utils/tutorial_utils.py#L174) that creates a simulation history from past observations similar to what is being done when [initializing](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/simulation/history/simulation_history_buffer.py#L162) a simulation history buffer from scenario

**Comment by christopher-motional** [comment]
You can also see the visualization [callback](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/training/callbacks/visualization_callback.py) for visualizing [features](https://github.com/motional/nuplan-devkit/tree/master/nuplan/planning/training/preprocessing/features) that get provided to ml planners

**Comment by Syzygianinfern0** [comment]
Thanks! Is there any existing method implemented to export simulations as mp4s?

**Comment by christopher-motional** [comment]
We don't support exporting simulations as mp4s, however you can use nuBoard (go to the Scenario tab) to visualize the scenarios associated with a set of simulations you generate much like a video file -- it also has a tab for quickly jumping between scenarios. You can see the latter part of the [framework tutorial](https://github.com/motional/nuplan-devkit/blob/master/tutorials/nuplan_framework.ipynb) for an example of how to use it

**Comment by Syzygianinfern0** [comment]
> perhaps you can [visualize the scenarios](https://github.com/motional/nuplan-devkit/blob/master/tutorials/utils/tutorial_utils.py?rgh-link-date=2023-07-18T23%3A06%3A58Z#L216) the planner input is extracted from similar to what's being done in the [scenario visualization tutorial](https://github.com/motional/nuplan-devkit/blob/master/tutorials/nuplan_scenario_visualization.ipynb?rgh-link-date=2023-07-18T23%3A06%3A58Z). You can see [here](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/simulation/simulation.py?rgh-link-date=2023-07-18T23%3A06%3A58Z#L140) where the PlannerInput is constructed. 

@christopher-motional this function requires a "scenario" object. How can I provide the input of the `current_state` and potentially the "`next_state`" so that I can visualize the movement of the ego vehicle for a single call of the `planner.compute_trajectory()`?

**Comment by patk-motional** [comment]
It is easiest if you use the simulation framework.

Here is an example of running an open_loop simulation.

First, run the simulation.
```python nuplan/planning/script/run_simulation.py +simulation=open_loop_boxes planner=simple_planner```

Inspect it using nuBoard.
```python nuplan/planning/script/run_nuboard.py```
