### ISSUE TITLE
Obtain a bev map like NuScenes

### ISSUE THREAD

**Issue by Frandre** [motional/nuplan-devkit#339]
I noticed that you have a function, get_map_mask, in NuPlanMapExplorer so that one can obtain a map with pre-defined layers and angles at some location. However, when I run it today it says that:
*** AttributeError: 'NuPlanMap' object has no attribute 'vector_polygon_layers'
After a second look, it seems to me that attribute 'vector_polygon_layers' no longer exists in NuPlanMap. 

My question is whether we have alternative options to fulfill this function. If yes, which function should I turn to?

--------- More details --------
I am expecting to have something like:
map_mask = nusc_map.get_map_mask(patch_box, patch_angle, layer_names, canvas_size)
 in [NuScenes map tutorial](https://www.nuscenes.org/tutorials/map_expansion_tutorial.html). 

Your help is appreciated.

**Comment by Frandre** [comment]
@christopher-motional   could you please help me out if possible. Thanks!

**Comment by patk-motional** [comment]
Hi @Frandre,

We've developed a new [map interface](https://github.com/motional/nuplan-devkit/blob/master/nuplan/common/maps/nuplan_map/nuplan_map.py). There should be more functionalities there.

**Comment by Frandre** [comment]
> Hi @Frandre,
> 
> We've developed a new [map interface](https://github.com/motional/nuplan-devkit/blob/master/nuplan/common/maps/nuplan_map/nuplan_map.py). There should be more functionalities there.

Hi @patk-motional , thanks for your response. 

Would you mind referring to the new function that corresponds to the original get_map_mask in in NuPlanMapExplorer so that one can obtain a map with pre-defined layers and angles at some location? I am sorry but I could not find one myself.

**Comment by patk-motional** [comment]
The closest thing that we have is probably this [function](https://github.com/motional/nuplan-devkit/blob/master/nuplan/common/maps/nuplan_map/nuplan_map.py#L109). You will have to apply a mask yourself something [like this](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/training/preprocessing/features/raster_utils.py#L179)
