### ISSUE TITLE
Get sample with TrafficLightStatusType=RED in nuPlan v0.2?

### ISSUE THREAD

**Issue by dougefla** [motional/nuplan-devkit#34]
Hi, thank you for your great work of the sufficient dataset and the dev kit!

I'm working with the nuPlan v0.2 (nuplan_v0.2.db), and some samples with red trafficlight are needed for my model. When I was traversing the dataset with subsample_ratio=0.01 and limit_scenarios_per_type=1000, I found all of the traversed samples are marked with TrafficLightStatusType=GREEN. I wonder if the current dataset has any sample with TrafficLightStatusType=RED? Or did I miss anything?

Here is how I was getting the TrafficLightStatusType of each scenerio (Under self-defined XXXFeatureBuilder):
```
    def get_features_from_scenario(self, scenario: AbstractScenario) -> Raster:
        ......
        # Get trafficlight info
        trafficlight: List[TrafficLightStatusData] = scenario.get_traffic_light_status_at_iteration(iteration=0)
        trafficlight_dict = {tl_statustype:[] for tl_statustype in TrafficLightStatusType}
        ......
```

**Comment by holger-motional** [comment]
Hi. Red traffic lights will be added for the nuPlan v1.0 release in April. For now we just have green and unknown (red or unobserved) statuses.

**Comment by holger-motional** [comment]
Please note also that even the green lights in v0.2 were broken, as the traffic light indices did not match the ones in the map :-(. This has been fixed and will be released soon.

**Comment by dougefla** [comment]
OK, I see. Thanks.

**Comment by HaodongLi-Hub** [comment]
> Hi, thank you for your great work of the sufficient dataset and the dev kit!
> 
> I'm working with the nuPlan v0.2 (nuplan_v0.2.db), and some samples with red trafficlight are needed for my model. When I was traversing the dataset with subsample_ratio=0.01 and limit_scenarios_per_type=1000, I found all of the traversed samples are marked with TrafficLightStatusType=GREEN. I wonder if the current dataset has any sample with TrafficLightStatusType=RED? Or did I miss anything?
> 
> Here is how I was getting the TrafficLightStatusType of each scenerio (Under self-defined XXXFeatureBuilder):
> 
> ```
>     def get_features_from_scenario(self, scenario: AbstractScenario) -> Raster:
>         ......
>         # Get trafficlight info
>         trafficlight: List[TrafficLightStatusData] = scenario.get_traffic_light_status_at_iteration(iteration=0)
>         trafficlight_dict = {tl_statustype:[] for tl_statustype in TrafficLightStatusType}
>         ......
> ```

Hi, can you share me with nuplan v0.2? I can not find it in the website, that confused me a lot! Thanks, really appreciate!

**Comment by WahabF** [comment]
Hello, Is this issue resolved in the latest version of NuPlan?
