### ISSUE TITLE
Closest Lane Information

### ISSUE THREAD

**Issue by NishkaArora** [motional/nuplan-devkit#340]
I'm trying to find the closest lane to an (x, y) position on the nuplan_map. Ideally, a discretized lane representation (such as a sequence of points that trace the lane that the ego vehicle is on).

I see that in test_get_lane you use the get_one_map_object. Is this the same as what I described? Is that the best way to get what I'm looking for?

Thanks!

**Comment by patk-motional** [comment]
Hi @NishkaArora,

[get_distance_to_nearest_map_object](https://github.com/motional/nuplan-devkit/blob/master/nuplan/common/maps/nuplan_map/nuplan_map.py#L180) is probably better suited
