### ISSUE TITLE
Simulation failed

### ISSUE THREAD

**Issue by shubaozhang** [motional/nuplan-devkit#35]
![image](https://user-images.githubusercontent.com/24953124/157157766-28342e78-0907-425f-a440-09fd2ed60c00.png)

import os
import hydra
import tempfile
from pathlib import Path
from nuplan.planning.script.run_simulation import main as main_simulation

# Location of path with all simulation configs
CONFIG_PATH = '../nuplan-devkit/nuplan/planning/script/config/simulation'
CONFIG_NAME = 'default_simulation'

# Create a temporary directory to store the cache and experiment artifacts
#SAVE_DIR = Path(tempfile.gettempdir()) / 'tutorial_nuplan_framework'  # optionally replace with persistent dir
SAVE_DIR = '/home/qcraft/nuplan/simulation/'  # optionally replace with persistent dir

# Name of the experiment
EXPERIMENT = 'vector'

# Get the checkpoint of the trained model
#LOG_DIR = '/home/qcraft/nuplan/experiments/'
#last_experiment = sorted(os.listdir(LOG_DIR))[-1]
#train_experiment_dir = sorted(Path(LOG_DIR).iterdir())[-1]
#checkpoint = sorted((train_experiment_dir / 'checkpoints').iterdir())[-1]

checkpoint = '/home/qcraft/nuplan/experiment/vector/2022.03.07.20.56.47/checkpoints/epoch=51.ckpt'

MODEL_PATH = str(checkpoint).replace("=", "\=")

# Select the planner and simulation challenge
PLANNER = 'ml_planner'  # [simple_planner, ml_planner]
#CHALLENGE = 'challenge_4_closed_loop_reactive_agents'  # [challenge_1_open_loop_boxes, challenge_3_closed_loop_nonreactive_agents, challenge_4_closed_loop_reactive_agents]
CHALLENGE = 'challenge_1_open_loop_boxes'  # [challenge_1_open_loop_boxes, challenge_3_closed_loop_nonreactive_agents, challenge_4_closed_loop_reactive_agents]
DATASET_PARAMS = [
    'scenario_builder=nuplan_mini',  # use nuplan mini database
    'scenario_builder/nuplan/scenario_filter=all_scenarios',  # initially select all scenarios in the database
    'scenario_builder.nuplan.scenario_filter.scenario_types=[nearby_dense_vehicle_traffic, ego_at_pudo, ego_starts_unprotected_cross_turn, ego_high_curvature]',  # select scenario types
    'scenario_builder.nuplan.scenario_filter.limit_scenarios_per_type=10',  # use 10 scenarios per scenario type
    'scenario_builder.nuplan.scenario_filter.subsample_ratio=0.1',  # subsample 20s scenario from 20Hz to 1Hz (0.05)
]

# Initialize configuration management system
hydra.core.global_hydra.GlobalHydra.instance().clear()  # reinitialize hydra if already initialized
hydra.initialize(config_path=CONFIG_PATH)

# Compose the configuration
cfg = hydra.compose(config_name=CONFIG_NAME, overrides=[
    f'experiment_name={EXPERIMENT}',
    f'group={SAVE_DIR}',
    'planner=ml_planner',
    'model=vector_model',
    'planner.model_config=${model}',  # hydra notation to select model config
    f'planner.checkpoint_path={MODEL_PATH}',  # this path can be replaced by the checkpoint of the model trained in the previous section
    f'+simulation={CHALLENGE}',
    *DATASET_PARAMS,
])

# Run the simulation loop
main_simulation(cfg)

# Fetch the filesystem location of the simulation results file for visualization in nuBoard (next section)
parent_dir = Path(SAVE_DIR) / EXPERIMENT
results_dir = list(parent_dir.iterdir())[0]  # get the child dir
nuboard_file_2 = [str(file) for file in results_dir.iterdir() if file.is_file() and file.suffix == '.nuboard'][0]
~

**Comment by holger-motional** [comment]
Thank you for creating the issue. Please provide the above screenshot as text so we can try to reconstruct your issue.

**Comment by holger-motional** [comment]
@shubaozhang Please see the above message.
