### ISSUE TITLE
Nuboard scenario can only display 150 frame?

### ISSUE THREAD

**Issue by shenwyf** [motional/nuplan-devkit#353]
Hi, developers:

I am recently try to run nuplan and get everything figured out, and when I use nuBoard to check my simulations, it seems that on the scenario tap, it only display the selected scenario for 150 frames. I just wondered is that the whole scenario duration in the database is that long, or for now the nuBoard can only display that short segment?

thanks for your help!

**Comment by JingyuQian** [comment]
By default a scenario should be 15s and sampled at 20Hz, giving you roughly 300 frames. If you use subsampling during simulation, something like `subsample_ratio_override=0.5`, that will give 150 frames.
