### ISSUE TITLE
fcntl library does not exist anymore on Windows

### ISSUE THREAD

**Issue by anubhavjetley2424** [motional/nuplan-devkit#354]
Hi, 
trying to run the nuplan_scenario_visualization.ipynb, but in the gpkg_mapsdb.py file the fcntl is used which is not existent on Windows. Im running Python 3.11.5, could that we why cause I haven't seen anyone else have this problem

**Comment by weiaiF** [comment]
I also encountered the same issue and resolved it following the advice on the website below [blog](https://blog.humh.cn/?p=408)
