### ISSUE TITLE
How to get the route from the dataset?

### ISSUE THREAD

**Issue by handsome-river** [motional/nuplan-devkit#38]
Hi!
I wonder if the 'routing' information is used in the  model training and refer stage and how to get it from the dataset?
About the 'routing' information, it is used to guide the direction of the car.It is like the car is  at the intersection, it needs the 'routing' information to know whether to turn left or right.
![image](https://user-images.githubusercontent.com/100257978/159911849-7c4167c9-782e-4c98-a37e-ccceb4092c6a.png)
Maybe my description is a little abstract, as shown by g in the figure

**Comment by holger-motional** [comment]
Hi @handsome-river. For the 1.0 release next month we are adding goal poses (x/y/yaw) and the sequence of road blocks leading to the goal. These can be used as a (coarse) route.

**Comment by handsome-river** [comment]
Thank you!

**Comment by trand2k** [comment]
Hi author, 
Can you tell me  how to get route from nuplan dataset ?
