### ISSUE TITLE
How to directly get other agents' trajectories?

### ISSUE THREAD

**Issue by Kguo-cs** [motional/nuplan-devkit#40]
The code provides the method to get the detections of other agents. How can I get their past and future trajectories directly?

**Comment by Kguo-cs** [comment]
By the way, there may be a bug in the "filter_agents" function of "agent_preprocessing.py". The "token" of the "box" should be changed into "track_token".

**Comment by gianmarco-motional** [comment]
I'll close the issue for inactivity. If you still are facing the problem with the current devkit version, feel free to reopen it!
