### ISSUE TITLE
Problems with loading images.

### ISSUE THREAD

**Issue by Haku247** [motional/nuplan-devkit#42]
Hi, I have a question about image in database. I wanna to see the .jpeg files from database file, but I see there only base64 token data in .db file.(maybe part of jpeg ?). Could you please explain how to export images? 
![深度截图_选择区域_20220419155104](https://user-images.githubusercontent.com/20238213/163953157-0ac87970-2348-4425-9520-4f1bcf8cd981.png)

**Comment by JingyuQian** [comment]
The raw images/lidar point clouds aren't available yet, as stated in their [website](https://www.nuscenes.org/nuplan#:~:text=It%20will%20also%20be%20possible%20to%20download%20raw%20sensor%20data%20(camera%20and%20lidar)%20for%20around%2010%25%20of%20the%20logs.%20However%2C%20this%20data%20will%20be%20made%20available%20later.). 

But there are some apis provided that allow you to get images/point clouds once they are available. For example, [this one](https://github.com/motional/nuplan-devkit/blob/7df9086472721aa3e4048e2d2596414a9ad78b22/nuplan/database/nuplan_db/models.py#L141). Hope it helps.

**Comment by JingyuQian** [comment]
Hi @wangsen1312,
I'm not affiliated with motional, just a developer lol. Hi @patk-motional, would you be able to answer this question? Thanks.

**Comment by dimitris-motional** [comment]
Hi @JingyuQian @wangsen1312, thanks for your interest in nuPlan! We're working on making available the lidar/camera raw sensor data after the public competition has started, towards the end of the year.
