### ISSUE TITLE
Is traffic light status data of NuPlan ready?

### ISSUE THREAD

**Issue by HermanZYZ** [motional/nuplan-devkit#46]
Hi, NuPlan team,
you mentioned that there is something wrong in traffic light status data in NuPlan. Is the new data released now? In the NuPlan website, the download link of data is still nuplan_v0.2. By the way, is there a page or website to log the updating messages of NuPlan data?

**Comment by patk-motional** [comment]
Hi!

We just released nuplan-v1.0. There, you should find traffic light information. Please give it a try and let us know if you encounter any problems.

**Comment by HermanZYZ** [comment]
@patk-motional By the way, there is another problem confused me. I used NuPlanScenario to generate a scenario with a given scenario type. It was so strange that the function 'get_number_of_iterations' output 400, 600 and even 800. 400 is right with duration 20s, 20 Hz and 1 down-sampling rate. It seems that it is due to the query of database. In the code, timestamp of initial lidarpc is used as the starting time, and +20s the end time. The query rule is 'lidarpc.timestamp > starting time and lidarpc.timestamp < end time'. It brings a problem that: if there exists two cars gathers data at the same time?

In NuPlan v0.2, I found that there were two pose with long distance and the same timestamp. I wonder has this problem been solved in NuPlan v1.0?

**Comment by patk-motional** [comment]
I don't quite follow your question. Do you mean if we had cars that were collecting data simultaneously? If that is your question then I don't think that was the case.

Can you elaborate on this "I found that there were two pose with long distance and the same timestamp."?
