### ISSUE TITLE
Requirements - Hydra and Torchmetrics Version

### ISSUE THREAD

**Issue by mh0797** [motional/nuplan-devkit#47]
I had trouble running the tutorial.
Turns out that the tutorial is not compatible with the most recent versions of torchmetrics and hydra-core

To get it to run, it's necessary to downgrade to torchmetrics==0.7.3 and hydra-core==1.1.1
I guess this should be added in the requirements

Errors:
for torchmetrics: get_num_classes is missing in new versions
for hydra-core: _resolve_target misses a second input argument full_key

**Comment by bAmpT** [comment]
The requirements should really include the package versions that are tested. I just had an issue with the metrics engine because I used a the scipy version that requires the `savgol_filter` to be used with odd window size only.

**Comment by patk-motional** [comment]
Hi all,

We've just recently updated the devkit and pinned versions for both torchmetrics and hydra-core. Please try reinstalling the devkit with the new requirements. Thank you for your patience!
