### ISSUE TITLE
Reactive agents do not have tracking tokens

### ISSUE THREAD

**Issue by aalec** [motional/nuplan-devkit#48]
Hello,

The Box3D objects for detections have a `track_token` variable which is very useful! However, when IDMAgents are created, their Box3D detections do not have these track_tokens. I'm not sure if this is on purpose or not but tracking tokens for the reactive agents (which are consistent with the agents from which they are created) would also be great feature.

**Comment by gianmarco-motional** [comment]
Hi!
This issue should have been solved with the `v0.2` release.

Feel free to reopen it if you encounter it again!
