### ISSUE TITLE
About LaneGCN

### ISSUE THREAD

**Issue by ZikangZhou** [motional/nuplan-devkit#5]
Thank you for releasing such an awesome planning benchmark! It will definitely stimulate the development of data-driven motion planners.

I notice that this devkit includes an implementation of LaneGCN. As far as I know, LaneGCN is an agent-centric motion forecasting model which normalizes the scenes with respect to the position and the heading of the "agent of interest". As this is a planning-oriented benchmark, are you treating the autonomous vehicle as the agent of interest and predicting the future trajectory of the autonomous vehicle? If so, do the training objectives include the regression losses for agents surrounding the autonomous vehicle?

**Comment by dimitris-motional** [comment]
Hi @ZikangZhou,

> Are you treating the autonomous vehicle as the agent of interest and predicting the future trajectory of the autonomous vehicle?

In this implementation the modeling is done in an ego-centric representation which is in the local frame (relative to ego).
The model [consumes](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/training/modeling/models/lanegcn_model.py#L108) and encodes features (past ego, agents, vector map) similar to the original LaneGCN, but [regresses](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/training/modeling/models/lanegcn_model.py#L158) a uni-modal future trajectory only for the ego.

> Do the training objectives include the regression losses for agents surrounding the autonomous vehicle?

No, as the model forecasts only the motion of the ego and not surrounding agents.
