### ISSUE TITLE
ValueError: Null layer: 'gen_lane_connectors_scaled_width_polygons'

### ISSUE THREAD

**Issue by niraj-bhujel** [motional/nuplan-devkit#55]
Hi, Thanks for the new planner tutorial. I am trying to run the 'nuplan_planner_tutorial.ipynb' but throw an error "AssertionError: No scenarios found to simulate!". 

I thought it there was some error in "scenario_filter.log" so I comment it like this;

`DATASET_PARAMS = [
    'scenario_builder=nuplan_mini',  # use nuplan mini database (2.5h of 8 autolabeled logs in Las Vegas)
    'scenario_filter=one_continuous_log',  # simulate only one log
    #'scenario_filter.log_names="[2021.07.16.20.45.29_veh-35_01095_01486]"',
    # select one log from test set of nuplan mini
    'scenario_filter.limit_total_scenarios=2',  # use 2 total scenarios
]
`
Now I can run the simulation, but encounter another problem: "RuntimeError: Metric Engine failed with: Null layer: 'gen_lane_connectors_scaled_width_polygons'".  

Appreciate your help!

**Comment by bAmpT** [comment]
It seems that in the new map version v1.0 the layer 'gen_lane_connectors_scaled_width_polygons' is removed. The error is in the `_get_all_lane_connectors(self, point: Point2D)` function of the nuplan_map.py file. I don't know if the layer was removed by mistake or if the function should be updated. 
For now I just modified it to first check for the points to be in the `lane_group_connectors` and looked for all `lane_connectors` with those ids. I not sure if it's working the same as before because I have not tested it well:

```python
# file: nuplan\common\maps\nuplan_map\nuplan_map.py
# ...
def _get_all_lane_connectors(self, point: Point2D) -> List[LaneConnector]:
    """
    Gets a list of lane connectors where its polygon overlaps the queried point.
    :param point: [m] x, y coordinates in global frame.
    :return: a list of lane connectors. An empty list if no lane connectors were found.
    """
    lane_group_connectors_df = self._load_vector_map_layer('lane_group_connectors')

    ids = lane_group_connectors_df.loc[lane_group_connectors_df.contains(geom.Point(point.x, point.y))][
        'fid'
    ].tolist()
    lane_group_connectors_ids = list(map(int, ids))

    lane_connectors_df = self._load_vector_map_layer('lane_connectors')
    ids = lane_connectors_df.loc[lane_connectors_df['lane_group_connector_fid'].isin(lane_group_connectors_ids)][
        'fid'
    ].tolist()

    lane_connector_ids = list(map(str, ids))

    return [self._get_lane_connector(lane_connector_id) for lane_connector_id in lane_connector_ids]
# ...
```

**Comment by patk-motional** [comment]
Hi!

Thank you for reporting the error. We've just re-uploaded the map. Please re-download the map and let us know if the problem persists

**Comment by JingyuQian** [comment]
Hi @patk-motional, I tried downloading the latest map and the problem still persists.
