### ISSUE TITLE
wrong：nuPlan Scenario Visualization

### ISSUE THREAD

**Issue by yangchentao-common** [motional/nuplan-devkit#57]
hi
at visualize_nuplan_scenarios(db)
have this problem
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/Desktop/nuplan-devkit-master/tutorials/utils/tutorial_utils.py:260, in visualize_nuplan_scenarios.<locals>.scenario_dropdown_handler(change)
    258 scenario = get_default_scenario_from_token(log_db, token)
    259 print(token)
--> 260 visualize_scenario(scenario)

File ~/Desktop/nuplan-devkit-master/tutorials/utils/tutorial_utils.py:161, in visualize_scenario(scenario, save_dir)
    159 map_factory = NuPlanMapFactory(scenario._db.maps_db)
    160 scenes = serialize_scenario(scenario)
--> 161 simulation_scenario_key = save_scenes_to_dir(scenes=scenes, scenario=scenario, save_dir=save_dir)
    162 visualize_scenarios([simulation_scenario_key], map_factory, Path(save_dir))

File ~/Desktop/nuplan-devkit-master/tutorials/utils/tutorial_utils.py:96, in save_scenes_to_dir(scenes, scenario, save_dir)
     93 with lzma.open(file, "wb", preset=0) as f:
     94     f.write(msgpack.packb(scenes))
---> 96 return SimulationScenarioKey(
     97     planner_name=planner_name, scenario_name=scenario_name, scenario_type=scenario_type, files=[file]
     98 )

TypeError: __init__() missing 2 required positional arguments: 'log_name' and 'nuboard_file_index'

**Comment by patk-motional** [comment]
Hi!

Which tutorial are you running?

FYI @kokseang-motional

**Comment by yangchentao-common** [comment]
> Hi!
> 
> Which tutorial are you running?
> 
> FYI @kokseang-motional

nuplan_scenario_visualization.ipynb

**Comment by patk-motional** [comment]
Thank you for flagging this - we are working on a fix!

**Comment by kokseang-motional** [comment]
That should be fixed now
