### ISSUE TITLE
Error in nuplan_framework.ipynb

### ISSUE THREAD

**Issue by ggosjw** [motional/nuplan-devkit#58]
When I RUN this block
![image](https://user-images.githubusercontent.com/87901530/174060397-28667eca-57a3-4968-b76e-84400880371a.png)
I encounter this error that:
![image](https://user-images.githubusercontent.com/87901530/174060604-dfc4a9d4-a96a-41b3-9454-e373f27a6511.png)
While I can really import nuplan like:
![image](https://user-images.githubusercontent.com/87901530/174060828-35db3094-3f13-4550-a9bd-187ad49908d9.png)

Thank you for your kind help!

**Comment by patk-motional** [comment]
Seems like there is an error with the installation. How did you install the devkit?
