### ISSUE TITLE
free(): invalid pointer

### ISSUE THREAD

**Issue by mh0797** [motional/nuplan-devkit#59]
The training crashes right after the last epoch when I run it from a python script.

The only error I get is
free(): invalid pointer

I am using the vector model, nuplan_mini, and ddp accelerator

Can you give me a hint where to search for an error?

**Comment by patk-motional** [comment]
Can you show us the full stack trace?

**Comment by mh0797** [comment]
As I said there is no error trace. See the stdout file below (you have to scroll to the very bottom).
[invalid_pointer_stdout.txt](https://github.com/motional/nuplan-devkit/files/8955463/invalid_pointer_stdout.txt)

This error seems to occur after the training finished, as all checkpoints (including the last epoch) are created correctly.

**Comment by mh0797** [comment]
You can find the command at the top of the file
`python ~/nuplan/nuplan-devkit/nuplan/planning/script/run_training.py experiment_name=tune_lanegcn py_func=train +training=training_vector_model scenario_builder=nuplan_mini scenario_builder.data_root=/home/aah1si/nuplan/dataset/nuplan_v1.0/mini scenario_filter.limit_total_scenarios=500 lightning.trainer.params.max_epochs=100 lightning.optimization.optimizer.learning_rate=1e-4 data_loader.params.batch_size=16 data_loader.params.num_workers=8`

**Comment by michael-noronha-motional** [comment]
Hey @mh0797, could you try latest master and let me know if you still see this? It may still be present and just non-deterministic/environment-specific, but I can no longer replicate.

**Comment by mh0797** [comment]
Hey,
i can confirm that it still happens. I also found out that the cause is an error in the destructor of the nuplandb_wrapper

**Comment by michael-noronha-motional** [comment]
Got it, thanks. Just to double-check, you rebuilt your `nuplan` virtual env since pulling master, right?

**Comment by mh0797** [comment]
Thanks for the hint. I just reinstalled the environment. The error seems to be gone. 
Thank you!
