### ISSUE TITLE
GEOS version warning

### ISSUE THREAD

**Issue by mh0797** [motional/nuplan-devkit#61]
I get the following when running a training or simulation

`warnings.warn(pid=318140) /home/aah1si/.conda/envs/nuplan/lib/python3.9/site-packages/geopandas/_compat.py:111: UserWarning: The Shapely GEOS version (3.10.2-CAPI-1.16.0) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow`

The requirements.txt does not fix a version for geopandas and Shapely.

**Comment by JingyuQian** [comment]
I managed to get around this warning after applying these steps:

1. Reinstall shapely: ```pip install --force-reinstall --no-binary shapely shapely```. Originally stated [here](https://github.com/shapely/shapely/issues/651#issuecomment-434818437).
2. If encounter ```OSError: /home/users/xxx/miniconda3/envs/nuplan/lib/libgeos_c.so: cannot open shared object file: No such file or directory```, then do ```conda install -c conda-forge pygeos``` to fix the missing library problem.
3. ```export LD_LIBRARY_PATH=$LD_LIBARRY_PATH:$HOME/miniconda3/env/nuplan/lib``` to include lib search path.

Those should fix the warning. 

I also had a problem of ```OSError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/users/xxx/miniconda3/envs/nuplan/lib/libgeos_c.so)``` which was fixed by installing gcc-6 using conda.

**Comment by gianmarco-motional** [comment]
Hi @JingyuQian!
Thanks for sharing your solution. We are aware of it, we are just trying to make the installation as seamless as possible.
We should have an update soon!

**Comment by mh0797** [comment]
Hi @gianmarco-motional.
is there an update on this ? The issue still persists with the version 0.3 of the devkit.

**Comment by patk-motional** [comment]
Yes, we are aware of this. Unfortunately, there is no clean way to bake this into the installation instructions. We are looking to silence the warning in run_training.py and run_simulation.py. This will be a part of the v0.4 update coming put soon

**Comment by michael-motional** [comment]
Hey @mh0797, this should be resolved on current master now for the most common workflows. In case you see the error again, the next release should fully squash it.
