### ISSUE TITLE
TrafficLightStatusData.stop_line_id cannot find in the map

### ISSUE THREAD

**Issue by yangchentao-common** [motional/nuplan-devkit#64]
hi!
when i try to use the "NuPlanScenario.get_traffic_light_status_at_iteration(0)" to get the stop_line_id and lane_connector_id,  it seems that i got the wrong id,because when i use the id to get the element "nuplan_map/utils.py get_element_with_fid", it was could not find
` File "/home/yangchentao/Desktop/nuplan-devkit-master/nuplan/common/maps/nuplan_map/stop_line.py", line 10, in __init__
    self._stop_line = get_element_with_fid(self._stop_lines_df, "fid", stop_line_id)
  File "/home/yangchentao/Desktop/nuplan-devkit-master/nuplan/common/maps/nuplan_map/utils.py", line 71, in get_element_with_fid
    assert len(matching_rows) > 0, f"Could not find the desired key = {desired_key}"
AssertionError: Could not find the desired key = 79877`

**Comment by YFHhhhhh** [comment]
Hi, I'm learing nuplan too. Shall we learn together? I want to ask you some questions,please. This is my weChat:yfh963963

**Comment by patk-motional** [comment]
Hi!

Have you updated to nuplanv1.0? `get_traffic_light_status_at_iteration` should only retrieve `lane_connector_id`. We have deprecated getting `stop_line_id` and using it to represent traffic light status. Let me know if you are still running into problems

**Comment by yangchentao-common** [comment]
thanks
