### ISSUE TITLE
Question:Unable to run "nuplan_planner_tutorial" successfully

### ISSUE THREAD

**Issue by YFHhhhhh** [motional/nuplan-devkit#66]
**I run the "launch simulation(within the notebook)" code block, but failed.
It says "AssertionError: No scenarios found to simulate!".
Please help me!!!**

**error:**
AssertionError                            Traceback (most recent call last)
/home/didiq/nuplan-devkit/tutorials/nuplan_planner_tutorial.ipynb Cell 21' in <cell line: 6>()
      3 planner = SimplePlanner(horizon_seconds=10.0, sampling_time=0.25, acceleration=[0.0, 0.0])
      5 # Run the simulation loop (real-time visualization not yet supported, see next section for visualization)
----> 6 main_simulation(cfg, planner)
      8 # Fetch the filesystem location of the simulation results file for visualization in nuBoard (next section)
      9 results_dir = list(list(Path(SAVE_DIR).iterdir())[0].iterdir())[0]  # get the child dir 2 levels in

File ~/nuplan-devkit/nuplan/planning/script/run_simulation.py:76, in run_simulation(cfg, planners)
     73     common_builder.profiler.save_profiler(profiler_name)
     75 logger.info('Running simulation...')
---> 76 run_runners(runners=runners, common_builder=common_builder, cfg=cfg, profiler_name='running_simulation')
     77 logger.info('Finished running simulation!')

File ~/nuplan-devkit/nuplan/planning/script/utils.py:123, in run_runners(runners, common_builder, profiler_name, cfg)
    113 def run_runners(
    114     runners: List[AbstractRunner], common_builder: CommonBuilder, profiler_name: str, cfg: DictConfig
    115 ) -> None:
    116     """
    117     Run a list of runners.
    118     :param runners: A list of runners.
   (...)
    121     :param cfg: Hydra config.
    122     """
...
    124     if common_builder.profiler:
    125         # Start simulation running profiling
    126         common_builder.profiler.start_profiler(profiler_name)

AssertionError: No scenarios found to simulate!

**Comment by kokseang-motional** [comment]
Hey @YFHhhhhh 
Please change 
`scenario_filter.log_name` in `DATASET_PARAMS` to

`"scenario_filter.log_names=['2021.07.16.20.45.29_veh-35_01095_01486']",`

**Comment by YFHhhhhh** [comment]
Thank you so much @kokseang-motional , it works!

**Comment by jiushuw** [comment]
Hi, in my code "DATASET_PARAMS" is already "scenarios_filter.log_names" but I am meeting the same error.
Sorry I am new to nuPlan and currently didn't find any information about this error. Pls help.

File ~/nuplan-devkit/nuplan/planning/script/run_simulation.py:79, in run_simulation(cfg, planners)
     76     common_builder.profiler.save_profiler(profiler_name)
     78 logger.info('Running simulation...')
---> 79 run_runners(runners=runners, common_builder=common_builder, cfg=cfg, profiler_name='running_simulation')
     80 logger.info('Finished running simulation!')

File ~/nuplan-devkit/nuplan/planning/script/utils.py:133, in run_runners(runners, common_builder, profiler_name, cfg)
    123 def run_runners(
    124     runners: List[AbstractRunner], common_builder: CommonBuilder, profiler_name: str, cfg: DictConfig
    125 ) -> None:
    126     """
    127     Run a list of runners.
    128     :param runners: A list of runners.
   (...)
    131     :param cfg: Hydra config.
    132     """
--> 133     assert len(runners) > 0, 'No scenarios found to simulate!'
    134     if common_builder.profiler:
    135         # Start simulation running profiling
    136         common_builder.profiler.start_profiler(profiler_name)

AssertionError: No scenarios found to simulate!
