### ISSUE TITLE
Question:how to get the lane boundary in the map?

### ISSUE THREAD

**Issue by YFHhhhhh** [motional/nuplan-devkit#70]
Hi, I didn't find the function to get the lane boundary in the map? Is there any function to do this?

Also, I think a toturial to introduce the api like nuScence is necessary and helpful.

**Comment by patk-motional** [comment]
Hi @YFHhhhhh, 

We are working towards that exact feature. Soon you should be able to query the lane boundaries from a lane object. We hope to have it out by the latest end of next week. 

The map API is still under heavy development so a tutorial for it will be out of date very quickly. We will reevaluate in the future if the tutorial is necessary.

**Comment by gsg213** [comment]
Hello @patk-motional and @YFHhhhhh ,

Was this feature developed in the api? or How did you manage to obtain the boundaries in the map?

Thank you!
