### ISSUE TITLE
How the map storage the lanes? And how to get the driveable lanes?

### ISSUE THREAD

**Issue by YFHhhhhh** [motional/nuplan-devkit#73]
Hi~, I read the map api recently, but I have some questions here:
1.How the map storage the lanes?
   In the map api, I find `incoming_edges()` and `outgoing_edges()` functions, whitch looks like a graph.But as shown below, if the ego_vehicle is in lane5 now, which lanes are the incoming edges to lane5, and which lanes are the outgoing egdes from lane5? And what's the order of the edges in a List[NuPlanLane]?
---------- ----------- --------------
   lane1                          lane4                     lane7    ---> drive direction
---------- ----------- --------------
   lane2                          lane5                     lane8    ---> drive direction
---------- ----------- --------------
   lane3                          lane6                     lane9    ---> drive direction
---------- ----------- --------------
2.If the ego vehicle driving in lane5, and the lane4 and lane6 are also drivable, how can I get lane4 and lane6, are they connected to lane5? This is important for a planner to get the search boundary.
3.I read the code and find the lane is storage as a polygon, now we consider a lane as a rectangle, but how I know which two edges are the lane boundary?
Sorry to ask so many questions, but it really confuses me.

**Comment by patk-motional** [comment]
Hi @YFHhhhhh,

1. The structure of our map at lane level is `lane -> lane_connector -> lane -> lane_connector`. The situation in your diagram should not occur. Following your thought, `incoming_edges()` and `outgoing_edges()` will return a list that indicates how many incoming or outgoing edges are connected to that object. For example, a lane can have many lane_connectors outgoing from it. Hence, a list is returned. There is no ordering.

2. As for adjacent lanes, we are introducing an interface to query neighboring lanes very soon.

3. In our next PR #75, we are adding an interface for lane boundaries.

Hope that addresses all of your questions!

**Comment by patk-motional** [comment]
1. I'm not sure what you mean by sections. I'm not familiar with other HD maps

2. We do provide routes in the form of roadblocks ids for each scenario. This is a list of roadblock ids that leads to the goal pose. This is given to each planner at initialization [here](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/simulation/planner/abstract_planner.py#L109). From there, you will need to extract the baseline from the map yourself

**Comment by YFHhhhhh** [comment]
@patk-motional Thank you for your reply!
Could you please tell me how to get the route baseline by roadblock ids? The pipline I can think is that traversal the lanes in the lane graph from the ego state and judge if the ids == roadblcok ids, and then get the baseline from the lane.Is that right? Or there are better method?

And what's the physical meaning of roadblock? Why a roadblock can contain a lane? It's kind of confusing.

**Comment by christopher-motional** [comment]
Hi @YFHhhhhh,
You can get the list of lanes or lane connectors comprising a roadblock or roadblock connector, respectively, using the interior_edges() method of an extracted roadblock/roadblock connector. You can then extract baselines individually for the lanes/lane connectors. Note that this will give you a collection of unordered baselines rather than a single connected reference line for the route, as routes are expressed at the roadblock instead of the lane level.

**Comment by YFHhhhhh** [comment]
@patk-motional @christopher-motional Thank you so much! It really helps!
