### ISSUE TITLE
About complete scenario tags and cut in scenarios

### ISSUE THREAD

**Issue by fsgdrq** [motional/nuplan-devkit#78]
How can I get a list of all possible scenario tags?

For example I downloaded a v1.0 (mini) dataset and output all the matching tags, but I don't seem to find any tag related to cut in. In fact I want to find all the scenarios related to other agents cut in.

Anyway, thanks again for this open source tool and the dataset!

**Comment by patk-motional** [comment]
Hi @fsgdrq,

We don't have cut-in scenarios mined or labeled unfortunately. We are in the process of updating our webpage with the latest data from the v1.0 dataset. This includes the list of all available scenarios

**Comment by fsgdrq** [comment]
Get it. Thanks!
