### ISSUE TITLE
nuPlan paper table comparison

### ISSUE THREAD

**Issue by perone** [motional/nuplan-devkit#80]
Reposting here as suggested in (https://forum.nuscenes.org/t/nuplan-paper-comparison-table/797):

Hello ! I was reading the nuPlan paper (https://arxiv.org/abs/2106.11810) where the Table 1 (shown below):
![image](https://user-images.githubusercontent.com/412328/178949039-ca1139b4-ff14-478e-a712-3ea5b1809494.png)

Is showing that the Lyft dataset doesn't have Closed-loop evaluation and that it has a "prediction" in the Type column.

As a suggestion, I would review the table because in [L5kit](https://github.com/woven-planet/l5kit) there is a closed-loop evaluation with many closed-loop metrics available since 2021 (before the nuPlan paper publication). Not only there is a simulator but also a RL environment where rollouts can be done and use rewards from closed-loop metrics as well. 
There is also an entire section about Planning where there was even a paper released using it for training a planner in closed-loop. Anyway, the table doesn't seem to reflect the current state of the framework.

**Comment by patk-motional** [comment]
Hi @perone,

Sorry for the super late reply. Thank you for pointing this out. We are in the process of reviewing the paper to make it more accurate

**Comment by perone** [comment]
No problem, thanks a lot for the reply @patk-motional.

**Comment by patk-motional** [comment]
Hi @perone, 

Sorry for the delay, does something like this suffice?
![image](https://user-images.githubusercontent.com/95635553/221607456-ed8b7adb-20ec-47cd-8132-9601882f67a8.png)

**Comment by perone** [comment]
Thanks for the quick reply @patk-motional, this sounds fine. I think the type can also be Pred+Plan (also for nuPlan no ?) because it can be used for agent prediction tasks as well, but up to you.

**Comment by patk-motional** [comment]
That's true, we're updating the paper now

**Comment by nightrome** [comment]
After looking into this we have decided to update the paper to state that your dataset provides a closed-loop planning tutorial, but no official benchmark, which is really the emphasize of nuPlan.
