### ISSUE TITLE
Inconsistent map files downloaded from the website

### ISSUE THREAD

**Issue by JingyuQian** [motional/nuplan-devkit#81]
Hello, I'm experiencing the same issue #55 here, and after re-downloading the map the problem still persists. 

The md5sum claimed by the website is:
![websitemd5](https://user-images.githubusercontent.com/13508878/179089553-7f51e024-9ea2-4409-8e4e-aabee71e9837.png)

While the downloaded version (tested both US and Asia links, both md5 are the same) is:
![calced](https://user-images.githubusercontent.com/13508878/179089661-dbbb2a55-8d07-42ce-9d3e-287f7bb20c81.png)

So it looks like there is an inconsistency problem. Appreciate it if it can be fixed promptly.

**Comment by patk-motional** [comment]
Hi @JingyuQian,

Thanks for raising this. The hash on the website has yet to be updated. `7dc203cf3b411f4fd2f9a265004ce0dd` is the correct one

Can you make sure that the devkit is using the newly downloaded map by replacing the contents in /data/sets/maps/?

**Comment by JingyuQian** [comment]
Hi @patk-motional, thanks for the prompt reply! Yes, it works on my side now.
