### ISSUE TITLE
empty vector_map causes vector_model to crash

### ISSUE THREAD

**Issue by mh0797** [motional/nuplan-devkit#82]
Hi,

Training the vector model results in the following error:
`RuntimeError: mat1 and mat2 shapes cannot be multiplied (0x128 and 134x128)` in "lanegcn_utils.py", line 561 

I managed to find out that the reason for this is, that for some scenarios the VectorMap.traffic_light_data is an empty list. I further noticed that this is the case if the number of lane_segments returned in `get_neighbor_vector_map` in "vector_map_feature_builder", line 133 is equal to 0.

For instance check scenario token 1e00d42ba8095cb3 in log 2021.09.15.11.49.23_veh-28_00693_01062

If model.vector_map_feature_radius is increased it works though.

**Comment by patk-motional** [comment]
Hi @mh0797,

Is this occurring during training or simulation?

**Comment by patk-motional** [comment]
Hi @mh0797,

Can you send us your command so that we can try to replicate this?

**Comment by mh0797** [comment]
Hi,

This is the command I used.
```
python ~/nuplan/nuplan-devkit/nuplan/planning/script/run_training.py \
	experiment_name=vector_model_error\
	scenario_filter.num_scenarios_per_type=150000 \
	data_loader.params.batch_size=16 \
    data_loader.params.num_workers=32 \
	cache.force_feature_computation=true \
	cache.cache_path=\
    py_func=train \
    +training=training_vector_model \
    scenario_builder=nuplan_mini \
        lightning.trainer.params.max_epochs=1 \
    lightning.optimization.optimizer.learning_rate=1e-5 \
scenario_filter.scenario_types="[accelerating_at_crosswalk, accelerating_at_stop_sign, accelerating_at_stop_sign_no_crosswalk, accelerating_at_traffic_light, accelerating_at_traffic_light_with_lead, accelerating_at_traffic_light_without_lead, behind_bike, behind_long_vehicle, behind_pedestrian_on_driveable, behind_pedestrian_on_pickup_dropoff, changing_lane, changing_lane_to_left, changing_lane_to_right, following_lane_with_lead, following_lane_with_slow_lead, following_lane_without_lead, high_lateral_acceleration, high_magnitude_jerk, high_magnitude_speed, low_magnitude_speed, medium_magnitude_speed, near_barrier_on_driveable, near_construction_zone_sign, near_high_speed_vehicle, near_long_vehicle, near_multiple_pedestrians, near_multiple_vehicles, near_pedestrian_at_pickup_dropoff, near_pedestrian_on_crosswalk, near_pedestrian_on_crosswalk_with_ego, near_trafficcone_on_driveable, on_all_way_stop_intersection, on_carpark, on_intersection, on_pickup_dropoff, on_stopline_crosswalk, on_stopline_stop_sign, on_stopline_traffic_light, on_traffic_light_intersection, starting_high_speed_turn, starting_left_turn, starting_low_speed_turn, starting_protected_cross_turn, starting_protected_noncross_turn, starting_right_turn, starting_straight_stop_sign_intersection_traversal, starting_straight_traffic_light_intersection_traversal, starting_unprotected_cross_turn, starting_unprotected_noncross_turn, stationary, stationary_at_crosswalk, stationary_at_traffic_light_with_lead, stationary_at_traffic_light_without_lead, stationary_in_traffic, stopping_at_crosswalk, stopping_at_stop_sign_no_crosswalk, stopping_at_stop_sign_with_lead, stopping_at_stop_sign_without_lead, stopping_at_traffic_light_with_lead, stopping_at_traffic_light_without_lead, stopping_with_lead, traversing_crosswalk, traversing_intersection, traversing_narrow_lane, traversing_pickup_dropoff, traversing_traffic_light_intersection, waiting_for_pedestrian_to_cross]"
```

However, you should also be able to reproduce this by training the vector model using the few_training_samples scenariofilter and replacing the first log (train) with the one mentioned above (log 2021.09.15.11.49.23_veh-28_00693_01062)

**Comment by patk-motional** [comment]
I am able to recreate the issue. Let me look in to this

**Comment by patk-motional** [comment]
Hi @mh0797,

For the vector model, we recommend that you cache your feature before training it. The reason is, that we check if the feature is [valid](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/training/preprocessing/features/vector_map.py#L90) before caching. However, this mechanism is not applicable when training without caching.

We will work to apply this to the non-caching training pipeline as well in the future. For the time being, the recommended way to train any model is to cache the features first.

**Comment by wangsen1312** [comment]
@patk-motional Thank you for your explanation, so how to do the cache before training?

**Comment by mh0797** [comment]
@wangsen1312 you can do 
```
python ~/nuplan/nuplan-devkit/nuplan/planning/script/run_training.py +training=training_vector_model py_func=cache cache.force_feature_computation=false data_augmentation="[]" cache.cache_path=/path/to/cache/
```

**Comment by wangsen1312** [comment]
@mh0797 Thank you for your information. I can get all the processed cache now. so How to use this cache to train the dataset other than online processing(which  parameter should I use)?

**Comment by mh0797** [comment]
You just have to set the cache path accordingly in your training config.
`cache.cache_path=/path/to/cached/dataset`

**Comment by wangsen1312** [comment]
@mh0797 Thank you for your help. But I still met the same issue. 
I don't know whether you can show the two complete command lines? Maybe I missed something important.

**Comment by mh0797** [comment]
@wangsen1312 Maybe the issue you are facing is related to #93 
The workaround that worked for me is to increase the map-range. that way, no scenario is empty and all features are valid.
You can do so by setting vector_map_feature_radius: 60 in vector_model.yaml config.
Note that this value has been increased from 20 to 40 in the latest update. 
You should then rerun the caching (in a new directory or delete the old one). If you are still facing problems, then please share the full error trace.
