### ISSUE TITLE
I got a black arrow when running run_nuboard.py,what happend?

### ISSUE THREAD

**Issue by liyangsensetime** [motional/nuplan-devkit#83]
![20220718-000656](https://user-images.githubusercontent.com/84004614/179410712-342dfd1f-ab5d-4504-8db3-f91e39fcff64.png)

**Comment by patk-motional** [comment]
Hi @liyangsensetime ,

Let me tag my colleague @kokseang-motional to take a look.

What command did you run nuBoard with?

**Comment by kokseang-motional** [comment]
Hi, could you please try ctrl + F5? It is probably that your browser doesn't get updated with the latest css

**Comment by liyangsensetime** [comment]
@kokseang-motional ,thanks for your reply ,it works!!!
