### ISSUE TITLE
KeyError: 'NUPLAN_MAPS_ROOT' for planner tutorial

### ISSUE THREAD

**Issue by BaiLiping** [motional/nuplan-devkit#84]
INFO:nuplan.planning.script.utils:Setting default NUPLAN_DATA_ROOT: /home/XXX/nuplan/dataset
INFO:nuplan.planning.script.utils:Setting default NUPLAN_EXP_ROOT: /home/XXX/nuplan/exp
Global seed set to 0
INFO:nuplan.planning.script.builders.main_callback_builder:Building MultiMainCallback...
INFO:nuplan.planning.script.builders.main_callback_builder:Building MultiMainCallback: 3...DONE!
Traceback (most recent call last):
  File "/home/zhubinglab/anaconda3/envs/nuplan/lib/python3.9/site-packages/omegaconf/resolvers/oc/__init__.py", line 33, in env
    return os.environ[key]
  File "/home/zhubinglab/anaconda3/envs/nuplan/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'NUPLAN_MAPS_ROOT'

**Comment by BaiLiping** [comment]
the repository path is set as specified by the instruction

**Comment by BaiLiping** [comment]
Problem solved, there are errors in your instruction. I will open a pull request.

**Comment by patk-motional** [comment]
Hi @BaiLiping,

Thanks for the PR. I have merged it

**Comment by cqqd3** [comment]
how to solve the problem?
![image](https://github.com/motional/nuplan-devkit/assets/70693411/99dc3fd7-3d82-4ba0-a4de-1ee5a968a6d3)

**Comment by wuhaoran111** [comment]
I also have this problem when i run the tutorials, does anyone know how to solve it?

![1721903711313](https://github.com/user-attachments/assets/1faaff8b-41f3-493d-afab-22441beb4398)

i have added the path in ~/.bashrc

`export NUPLAN_DATA_ROOT="~/wuhr/nuplan/dataset"
export NUPLAN_MAPS_ROOT="~/wuhr/nuplan/dataset/maps"
export NUPLAN_EXP_ROOT="~/wuhr/nuplan/exp"`

**Comment by yangtzech** [comment]
> I also have this problem when i run the tutorials, does anyone know how to solve it?
> 
> ![1721903711313](https://private-user-images.githubusercontent.com/52778907/352073662-1faaff8b-41f3-493d-afab-22441beb4398.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjQ5ODUsIm5iZiI6MTcyNDc2NDY4NSwicGF0aCI6Ii81Mjc3ODkwNy8zNTIwNzM2NjItMWZhYWZmOGItNDFmMy00OTNkLWFmYWItMjI0NDFiZWI0Mzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEzMTgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZjBkNzNkZjRmYjZmNjU3OGRkYWVhYTcwNWNlNDgwMGMwYzMzNzU5M2FjOWQwNzhiMzk4YzdhODBjZTljZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q1Ki-kIDFj7qUkyitzd_0PoMDOj6DaoiX1qCYFIQweY)
> 
> i have added the path in ~/.bashrc
> 
> ```
> export NUPLAN_DATA_ROOT="~/wuhr/nuplan/dataset"
> export NUPLAN_MAPS_ROOT="~/wuhr/nuplan/dataset/maps"
> export NUPLAN_EXP_ROOT="~/wuhr/nuplan/exp"
> ```
@wuhaoran111 
export NUPLAN_DATA_ROOT="$HOME/nuplan/dataset"
export NUPLAN_MAPS_ROOT="$HOME/nuplan/dataset/maps"
export NUPLAN_EXP_ROOT="$HOME/nuplan/exp"
