### ISSUE TITLE
Unable to launch training in the nuplan_framework.ipynb tutorial  

### ISSUE THREAD

**Issue by kanav532** [motional/nuplan-devkit#88]
The following is the error:

**TypeError: __init__() missing 2 required positional arguments: 'params' and 'orig'**

The complete log is as follows:
---------------------------------------------------------------------------
DatabaseError                             Traceback (most recent call last)
File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/engine/base.py:3280, in Engine._wrap_pool_connect(self, fn, connection)
   3279 try:
-> 3280     return fn()
   3281 except dialect.dbapi.Error as e:

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/pool/impl.py:382, in SingletonThreadPool.connect(self)
    380         return rec._checkout_existing()
--> 382 return _ConnectionFairy._checkout(self, self._fairy)

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/pool/base.py:868, in _ConnectionFairy._checkout(cls, pool, threadconns, fairy)
    867 if not fairy:
--> 868     fairy = _ConnectionRecord.checkout(pool)
    870     fairy._pool = pool

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/pool/base.py:476, in _ConnectionRecord.checkout(cls, pool)
    474 @classmethod
    475 def checkout(cls, pool):
--> 476     rec = pool._do_get()
    477     try:

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/pool/impl.py:364, in SingletonThreadPool._do_get(self)
    363     pass
--> 364 c = self._create_connection()
    365 self._conn.current = weakref.ref(c)

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/pool/base.py:256, in Pool._create_connection(self)
    254 """Called by subclasses to create a new ConnectionRecord."""
--> 256 return _ConnectionRecord(self)

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/pool/base.py:371, in _ConnectionRecord.__init__(self, pool, connect)
    370 if connect:
--> 371     self.__connect()
    372 self.finalize_callback = deque()

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/pool/base.py:666, in _ConnectionRecord.__connect(self)
    665     with util.safe_reraise():
--> 666         pool.logger.debug("Error on connect(): %s", e)
    667 else:
    668     # in SQLAlchemy 1.4 the first_connect event is not used by
    669     # the engine, so this will usually not be set

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py:70, in safe_reraise.__exit__(self, type_, value, traceback)
     69     if not self.warn_only:
---> 70         compat.raise_(
     71             exc_value,
     72             with_traceback=exc_tb,
     73         )
     74 else:

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/util/compat.py:208, in raise_(***failed resolving arguments***)
    207 try:
--> 208     raise exception
    209 finally:
    210     # credit to
    211     # https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/
    212     # as the __traceback__ object creates a cycle

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/pool/base.py:661, in _ConnectionRecord.__connect(self)
    660 self.starttime = time.time()
--> 661 self.dbapi_connection = connection = pool._invoke_creator(self)
    662 pool.logger.debug("Created new connection %r", connection)

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/pool/base.py:241, in Pool._should_wrap_creator.<locals>.<lambda>(crec)
    238 # all other cases, just wrap and assume legacy "creator" callable
    239 # thing
    240 else:
--> 241     return lambda crec: creator()

File ~/nuplan/nuplan-devkit/nuplan/database/common/db.py:544, in DB._create_db_instance(self)
    543 db = sqlite3.connect('file:{}?mode=ro'.format(self.table_root), uri=True, check_same_thread=False)
--> 544 db.execute('PRAGMA main.journal_mode = OFF;')
    545 db.execute('PRAGMA main.cache_size=10240;')

DatabaseError: database disk image is malformed

The above exception was the direct cause of the following exception:

DatabaseError                             Traceback (most recent call last)
File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py:62, in _call_target(target, *args, **kwargs)
     60             v._set_parent(None)
---> 62     return target(*args, **kwargs)
     63 except Exception as e:

File ~/nuplan/nuplan-devkit/nuplan/planning/scenario_builder/nuplan_db/nuplan_scenario_builder.py:73, in NuPlanScenarioBuilder.__init__(self, data_root, map_root, db_files, map_version, max_workers, verbose, scenario_mapping, vehicle_parameters, ground_truth_predictions)
     71 self._vehicle_parameters = vehicle_parameters if vehicle_parameters is not None else get_pacifica_parameters()
---> 73 self._db = NuPlanDBWrapper(
     74     data_root=data_root,
     75     map_root=map_root,
     76     db_files=db_files,
     77     map_version=map_version,
     78     max_workers=max_workers,
     79     verbose=verbose,
     80 )

File ~/nuplan/nuplan-devkit/nuplan/database/nuplan_db/nuplandb_wrapper.py:169, in NuPlanDBWrapper.__init__(self, data_root, map_root, db_files, map_version, max_workers, verbose)
    168 # Load nuPlan log DBs
--> 169 self._log_db_mapping = load_log_db_mapping(
    170     data_root=self._data_root,
    171     db_files=self._db_files,
    172     maps_db=self._maps_db,
    173     max_workers=self._max_workers,
    174     verbose=self._verbose,
    175 )
    176 logger.info(f'Loaded {len(self.log_dbs)} log DBs')

File ~/nuplan/nuplan-devkit/nuplan/database/nuplan_db/nuplandb_wrapper.py:103, in load_log_db_mapping(data_root, db_files, maps_db, max_workers, verbose)
    102     wrapped_iterable = tqdm(futures_iterable, total=len(futures), leave=False) if verbose else futures_iterable
--> 103     log_dbs = [future.result() for future in wrapped_iterable]
    105 # Sort databases based on their log name and hash them in a table.

File ~/nuplan/nuplan-devkit/nuplan/database/nuplan_db/nuplandb_wrapper.py:103, in <listcomp>(.0)
    102     wrapped_iterable = tqdm(futures_iterable, total=len(futures), leave=False) if verbose else futures_iterable
--> 103     log_dbs = [future.result() for future in wrapped_iterable]
    105 # Sort databases based on their log name and hash them in a table.

File ~/anaconda3/envs/nuplan/lib/python3.9/concurrent/futures/_base.py:439, in Future.result(self, timeout)
    438 elif self._state == FINISHED:
--> 439     return self.__get_result()
    441 self._condition.wait(timeout)

File ~/anaconda3/envs/nuplan/lib/python3.9/concurrent/futures/_base.py:391, in Future.__get_result(self)
    390 try:
--> 391     raise self._exception
    392 finally:
    393     # Break a reference cycle with the exception in self._exception

File ~/anaconda3/envs/nuplan/lib/python3.9/concurrent/futures/thread.py:58, in _WorkItem.run(self)
     57 try:
---> 58     result = self.fn(*self.args, **self.kwargs)
     59 except BaseException as exc:

File ~/nuplan/nuplan-devkit/nuplan/database/nuplan_db/nuplandb.py:80, in NuPlanDB.__init__(self, data_root, load_path, maps_db, verbose)
     79 nuplandb_models_dict["EgoPose"] = "ego_pose"
---> 80 super().__init__(table_names, nuplan_db, data_root, load_path, verbose, nuplandb_models_dict)

File ~/nuplan/nuplan-devkit/nuplan/database/common/db.py:377, in DB.__init__(self, table_names, models, data_root, db_path, verbose, model_source_dict)
    376 for table_name in self._table_names:
--> 377     logger.debug("{} {},".format(len(self._tables[table_name]), table_name))
    378 logger.debug("Done loading in {:.1f} seconds.\n".format(time.time() - start_time))

File ~/nuplan/nuplan-devkit/nuplan/database/common/db.py:263, in Table.__len__(self)
    258 """
    259 Return length of the records for the given queries. For example:
    260     nuplandb.log.__len()
    261 :return: Number of records.
    262 """
--> 263 return self._session.query(self._table.token).count()

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/orm/query.py:3163, in Query.count(self)
   3162 col = sql.func.count(sql.literal_column("*"))
-> 3163 return self._from_self(col).enable_eagerloads(False).scalar()

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/orm/query.py:2888, in Query.scalar(self)
   2887 try:
-> 2888     ret = self.one()
   2889     if not isinstance(ret, collections_abc.Sequence):

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/orm/query.py:2865, in Query.one(self)
   2848 """Return exactly one result or raise an exception.
   2849 
   2850 Raises ``sqlalchemy.orm.exc.NoResultFound`` if the query selects
   (...)
   2863 
   2864 """
-> 2865 return self._iter().one()

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/orm/query.py:2903, in Query._iter(self)
   2902 statement = self._statement_20()
-> 2903 result = self.session.execute(
   2904     statement,
   2905     params,
   2906     execution_options={"_sa_orm_load_options": self.load_options},
   2907 )
   2909 # legacy: automatically set scalars, unique

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/orm/session.py:1706, in Session.execute(self, statement, params, execution_options, bind_arguments, _parent_execute_state, _add_event, **kw)
   1702 if self.autocommit:
   1703     # legacy stuff, we can't use future_result w/ autocommit because
   1704     # we rely upon close_with_result, also legacy.  it's all
   1705     # interrelated
-> 1706     conn = self._connection_for_bind(bind, close_with_result=True)
   1707     execution_options = execution_options.union(
   1708         dict(future_result=False)
   1709     )

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/orm/session.py:1558, in Session._connection_for_bind(self, engine, execution_options, **kw)
   1557 assert self.autocommit
-> 1558 conn = engine.connect(**kw)
   1559 if execution_options:

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/engine/base.py:3234, in Engine.connect(self, close_with_result)
   3220 """Return a new :class:`_engine.Connection` object.
   3221 
   3222 The :class:`_engine.Connection` object is a facade that uses a DBAPI
   (...)
   3231 
   3232 """
-> 3234 return self._connection_cls(self, close_with_result=close_with_result)

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/engine/base.py:96, in Connection.__init__(self, engine, connection, close_with_result, _branch_from, _execution_options, _dispatch, _has_events, _allow_revalidate)
     92 else:
     93     self._dbapi_connection = (
     94         connection
     95         if connection is not None
---> 96         else engine.raw_connection()
     97     )
     99     self._transaction = self._nested_transaction = None

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/engine/base.py:3313, in Engine.raw_connection(self, _connection)
   3292 """Return a "raw" DBAPI connection from the connection pool.
   3293 
   3294 The returned object is a proxied version of the DBAPI
   (...)
   3311 
   3312 """
-> 3313 return self._wrap_pool_connect(self.pool.connect, _connection)

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/engine/base.py:3283, in Engine._wrap_pool_connect(self, fn, connection)
   3282 if connection is None:
-> 3283     Connection._handle_dbapi_exception_noconnection(
   3284         e, dialect, self
   3285     )
   3286 else:

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/engine/base.py:2117, in Connection._handle_dbapi_exception_noconnection(cls, e, dialect, engine)
   2116 elif should_wrap:
-> 2117     util.raise_(
   2118         sqlalchemy_exception, with_traceback=exc_info[2], from_=e
   2119     )
   2120 else:

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/util/compat.py:208, in raise_(***failed resolving arguments***)
    207 try:
--> 208     raise exception
    209 finally:
    210     # credit to
    211     # https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/
    212     # as the __traceback__ object creates a cycle

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/engine/base.py:3280, in Engine._wrap_pool_connect(self, fn, connection)
   3279 try:
-> 3280     return fn()
   3281 except dialect.dbapi.Error as e:

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/pool/impl.py:382, in SingletonThreadPool.connect(self)
    380         return rec._checkout_existing()
--> 382 return _ConnectionFairy._checkout(self, self._fairy)

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/pool/base.py:868, in _ConnectionFairy._checkout(cls, pool, threadconns, fairy)
    867 if not fairy:
--> 868     fairy = _ConnectionRecord.checkout(pool)
    870     fairy._pool = pool

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/pool/base.py:476, in _ConnectionRecord.checkout(cls, pool)
    474 @classmethod
    475 def checkout(cls, pool):
--> 476     rec = pool._do_get()
    477     try:

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/pool/impl.py:364, in SingletonThreadPool._do_get(self)
    363     pass
--> 364 c = self._create_connection()
    365 self._conn.current = weakref.ref(c)

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/pool/base.py:256, in Pool._create_connection(self)
    254 """Called by subclasses to create a new ConnectionRecord."""
--> 256 return _ConnectionRecord(self)

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/pool/base.py:371, in _ConnectionRecord.__init__(self, pool, connect)
    370 if connect:
--> 371     self.__connect()
    372 self.finalize_callback = deque()

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/pool/base.py:666, in _ConnectionRecord.__connect(self)
    665     with util.safe_reraise():
--> 666         pool.logger.debug("Error on connect(): %s", e)
    667 else:
    668     # in SQLAlchemy 1.4 the first_connect event is not used by
    669     # the engine, so this will usually not be set

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py:70, in safe_reraise.__exit__(self, type_, value, traceback)
     69     if not self.warn_only:
---> 70         compat.raise_(
     71             exc_value,
     72             with_traceback=exc_tb,
     73         )
     74 else:

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/util/compat.py:208, in raise_(***failed resolving arguments***)
    207 try:
--> 208     raise exception
    209 finally:
    210     # credit to
    211     # https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/
    212     # as the __traceback__ object creates a cycle

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/pool/base.py:661, in _ConnectionRecord.__connect(self)
    660 self.starttime = time.time()
--> 661 self.dbapi_connection = connection = pool._invoke_creator(self)
    662 pool.logger.debug("Created new connection %r", connection)

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/sqlalchemy/pool/base.py:241, in Pool._should_wrap_creator.<locals>.<lambda>(crec)
    238 # all other cases, just wrap and assume legacy "creator" callable
    239 # thing
    240 else:
--> 241     return lambda crec: creator()

File ~/nuplan/nuplan-devkit/nuplan/database/common/db.py:544, in DB._create_db_instance(self)
    543 db = sqlite3.connect('file:{}?mode=ro'.format(self.table_root), uri=True, check_same_thread=False)
--> 544 db.execute('PRAGMA main.journal_mode = OFF;')
    545 db.execute('PRAGMA main.cache_size=10240;')

DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
(Background on this error at: https://sqlalche.me/e/14/4xp6)

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
Input In [5], in <cell line: 4>()
      1 from nuplan.planning.script.run_training import main as main_train
      3 # Run the training loop, optionally inspect training artifacts through tensorboard (above cell)
----> 4 main_train(cfg)

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/hydra/main.py:44, in main.<locals>.main_decorator.<locals>.decorated_main(cfg_passthrough)
     41 @functools.wraps(task_function)
     42 def decorated_main(cfg_passthrough: Optional[DictConfig] = None) -> Any:
     43     if cfg_passthrough is not None:
---> 44         return task_function(cfg_passthrough)
     45     else:
     46         args = get_args_parser()

File ~/nuplan/nuplan-devkit/nuplan/planning/script/run_training.py:57, in main(cfg)
     53 worker = build_worker(cfg)
     55 if cfg.py_func == 'train':
     56     # Build training engine
---> 57     engine = build_training_engine(cfg, worker)
     59     # Run training
     60     logger.info('Starting training...')

File ~/nuplan/nuplan-devkit/nuplan/planning/training/experiments/training.py:59, in build_training_engine(cfg, worker)
     56 torch_module_wrapper = build_torch_module_wrapper(cfg.model)
     58 # Build the datamodule
---> 59 datamodule = build_lightning_datamodule(cfg, worker, torch_module_wrapper)
     61 # Update the learning rate parameters in multinode setting
     62 OmegaConf.set_struct(cfg, False)

File ~/nuplan/nuplan-devkit/nuplan/planning/script/builders/training_builder.py:56, in build_lightning_datamodule(cfg, worker, model)
     53 augmentors = build_agent_augmentor(cfg.data_augmentation) if 'data_augmentation' in cfg else None
     55 # Build dataset scenarios
---> 56 scenarios = build_scenarios(cfg, worker, model)
     58 # Create datamodule
     59 datamodule: pl.LightningDataModule = DataModule(
     60     feature_preprocessor=feature_preprocessor,
     61     splitter=splitter,
   (...)
     65     **cfg.data_loader.datamodule,
     66 )

File ~/nuplan/nuplan-devkit/nuplan/planning/script/builders/scenario_builder.py:148, in build_scenarios(cfg, worker, model)
    137 def build_scenarios(cfg: DictConfig, worker: WorkerPool, model: TorchModuleWrapper) -> List[AbstractScenario]:
    138     """
    139     Build the scenario objects that comprise the training dataset.
    140     :param cfg: Omegaconf dictionary.
   (...)
    143     :return: List of extracted scenarios.
    144     """
    145     scenarios = (
    146         extract_scenarios_from_cache(cfg, worker, model)
    147         if cfg.cache.use_cache_without_dataset
--> 148         else extract_scenarios_from_dataset(cfg, worker)
    149     )
    151     logger.info(f'Extracted {len(scenarios)} scenarios for training')
    152     assert len(scenarios) > 0, 'No scenarios were retrieved for training, check the scenario_filter parameters!'

File ~/nuplan/nuplan-devkit/nuplan/planning/script/builders/scenario_builder.py:130, in extract_scenarios_from_dataset(cfg, worker)
    123 def extract_scenarios_from_dataset(cfg: DictConfig, worker: WorkerPool) -> List[AbstractScenario]:
    124     """
    125     Extract and filter scenarios by loading a dataset using the scenario builder.
    126     :param cfg: Omegaconf dictionary.
    127     :param worker: Worker to submit tasks which can be executed in parallel.
    128     :return: List of extracted scenarios.
    129     """
--> 130     scenario_builder = build_scenario_builder(cfg)
    131     scenario_filter = build_scenario_filter(cfg.scenario_filter)
    132     scenarios: List[AbstractScenario] = scenario_builder.get_scenarios(scenario_filter, worker)

File ~/nuplan/nuplan-devkit/nuplan/planning/script/builders/scenario_building_builder.py:19, in build_scenario_builder(cfg)
     13 """
     14 Builds scenario builder.
     15 :param cfg: DictConfig. Configuration that is used to run the experiment.
     16 :return: Instance of scenario builder.
     17 """
     18 logger.info('Building AbstractScenarioBuilder...')
---> 19 scenario_builder = instantiate(cfg.scenario_builder)
     20 validate_type(scenario_builder, AbstractScenarioBuilder)
     21 logger.info('Building AbstractScenarioBuilder...DONE!')

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py:180, in instantiate(config, *args, **kwargs)
    177     _recursive_ = config.pop(_Keys.RECURSIVE, True)
    178     _convert_ = config.pop(_Keys.CONVERT, ConvertMode.NONE)
--> 180     return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
    181 else:
    182     raise InstantiationException(
    183         "Top level config has to be OmegaConf DictConfig, plain dict, or a Structured Config class or instance"
    184     )

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py:249, in instantiate_node(node, convert, recursive, *args)
    245                 value = instantiate_node(
    246                     value, convert=convert, recursive=recursive
    247                 )
    248             kwargs[key] = _convert_node(value, convert)
--> 249     return _call_target(target, *args, **kwargs)
    250 else:
    251     # If ALL or PARTIAL non structured, instantiate in dict and resolve interpolations eagerly.
    252     if convert == ConvertMode.ALL or (
    253         convert == ConvertMode.PARTIAL and node._metadata.object_type is None
    254     ):

File ~/anaconda3/envs/nuplan/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py:64, in _call_target(target, *args, **kwargs)
     62     return target(*args, **kwargs)
     63 except Exception as e:
---> 64     raise type(e)(
     65         f"Error instantiating '{_convert_target_to_string(target)}' : {e}"
     66     ).with_traceback(sys.exc_info()[2])

**TypeError: __init__() missing 2 required positional arguments: 'params' and 'orig'**

**Comment by chao-SFD** [comment]
I have also  encountered the problem：**TypeError: __init__() missing 2 required positional arguments: 'params' and 'orig'**,  and I don't know if it's the problem of **sqlalchemy** library.

**Comment by chao-SFD** [comment]
> I have also encountered the problem：**TypeError: **init**() missing 2 required positional arguments: 'params' and 'orig'**, and I don't know if it's the problem of **sqlalchemy** library.

I found that some of the previous DB files were corrupted.  After re-downloading and unpacking, the problem disappeared.

**Comment by patk-motional** [comment]
Hi @chao-SFD,

Good to hear that the problem got solved.
