### ISSUE TITLE
Bugs in the tutorial

### ISSUE THREAD

**Issue by MasterIzumi** [motional/nuplan-devkit#9]
Hi, it seems that there are small bugs in the tutorial `nuplan_framework.ipynb`:

- In `Prepare the training config`
```
LOG_DIR = str(SAVE_DIR / experiment_name)  -->  LOG_DIR = str(SAVE_DIR / EXPERIMENT)
```
- In `Launch simulation (within the notebook)`
```
results_dir = list(list(parent_dir.iterdir())[0].iterdir())[0]  -->  results_dir = list(parent_dir.iterdir())[0]
```
The child dir level seems wrong, 1 level is okay for my test. Same in the `Simulate a trained ML planner for comparison`.

**Comment by dimitris-motional** [comment]
Hi @MasterIzumi, thanks for reporting this issue, it has been fixed.
