### ISSUE TITLE
Question about the route_roadblock_ids.

### ISSUE THREAD

**Issue by YFHhhhhh** [motional/nuplan-devkit#90]
1. The route_roadblock_ids only include roadblock_ids or include both roadblock_ids and roadblock_connector_ids? 

2.A lane's(roadblock's) outgoing_edges must be lane_connctor(road_block_connector)?

**Comment by patk-motional** [comment]
Hi @YFHhhhhh 

1. Both - just a note that for some scenarios the route_roadblock_ids are buggy and we are working to release a revised version of the dataset to address this.
2. Yes, you are correct
