### ISSUE TITLE
Timeline for the 10% sensor data release

### ISSUE THREAD

**Issue by BaiLiping** [motional/nuplan-devkit#92]
hi there, is there a tentative timeline for the 10% sensor data release? I am interested in studying planning enabled perception, which would require real sensor data for my experiment. It would be helpful to have a timeline for the data release, even just a tentative one. 

Thanks.

**Comment by patk-motional** [comment]
Hi @BaiLiping,

We are prioritizing stabilizing the codebase and dataset for the planning competition. We will be releasing the sensor data after the competition has start. Linking an [answer](https://github.com/motional/nuplan-devkit/issues/42#issuecomment-1189931772) to a separate issue
