### ISSUE TITLE
heading of ego car

### ISSUE THREAD

**Issue by YFHhhhhh** [motional/nuplan-devkit#94]
What is the geometric meaning of ‘heading' in 'StateSE2' in nuPlan：
1.angle between centroid velocity and horizontal direction?
2.angle between body direction and horizontal direction?

**Comment by patk-motional** [comment]
StateSE2 is simply a dataclass that contains x, y, and heading. Now, the user must keep track of what frame the state is in and what it represents.

For example, if you took the ego state from the scenario that is in the global frame. Where x and y are the position in global coordinates. The heading is the angle of the `body direction` - as you put it - with the x axis of the global frame

**Comment by YFHhhhhh** [comment]
@patk-motional  Thanks!

**Comment by patk-motional** [comment]
Welcome :)
